### ISSUE TITLE
eventtap not firing

### ISSUE THREAD

**Issue by raineorshine** [Hammerspoon/hammerspoon#1743] opened 2018-04-11 18:06 UTC
I restored a Time Machine backup to a new machine and now `eventtap` events are not firing. I have isolated it in the below snippet. No errors appear in the Hammerspoon console. Any ideas of how to troubleshoot this next? Thanks!

OSX 10.13.3

```lua
print('THIS PRINTS TO THE CONSOLE')

hs.eventtap.new({ hs.eventtap.event.types.keyDown }, function(event)
  print('NEVER CALLED')
end):start()
```

**Comment by cmsj** [comment] 2018-04-11 18:36
@raineorshine did you check if Hammerspoon has Accessibility permissions?

**Comment by raineorshine** [comment] 2018-04-12 16:40
@cmsj Hammerspoon is listed and checked in the Privacy/Accessibility tab.

**Comment by raineorshine** [comment] 2018-04-12 16:45
I attempted the potential fix at http://mizage.clarify-it.com/d/6ervmn but encountered "Error: attempt to write a readonly database".

**Comment by raineorshine** [comment] 2018-04-17 21:37
Any ideas? I suspect it has to do with Accessibility but I am unsure how to reset it. Uninstalling and re-installing hammerspoon doesn't reset it.

**Comment by raineorshine** [comment] 2018-04-18 20:50
@latenitefilms Thank you, though unfortunately I tried it and I get an Error. ([previous comment](https://github.com/Hammerspoon/hammerspoon/issues/1743#issuecomment-380871150))

**Comment by raineorshine** [comment] 2018-04-18 21:33
I got my way around the Readonly Database error (it was locked by another process, which I could see by running `sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db 'select client from access'`). This completely removed Hammerspoon from the Accessibility list. I then was able to re-enable Accessibility, and it still doesn't work. Restarted both Hammerspoon and computer multiple times. Same behavior described in OP.

**Comment by latenitefilms** [comment] 2018-04-18 21:57
@raineorshine - Weird.

Have you tried re-downloading the latest Hammerspoon release from the website?

Maybe @cmsj or @asmagill might have some other suggestions?

**Comment by raineorshine** [comment] 2018-04-18 22:35
> Have you tried re-downloading the latest Hammerspoon release from the website?

Yes, I have tried this.

**Comment by raineorshine** [comment] 2018-04-18 22:36
It *must* be Accessibility... it shows all the symptoms of not having it enabled. It's just weird that every workaround and effort to enable it has failed.

**Comment by cmsj** [comment] 2018-04-18 22:47
You can double check the actual state of accessibility in the Hammerspoon Console:

`hs.accessibilityState()`

if it returns true, accessibility is actually enabled for HS.

**Comment by raineorshine** [comment] 2018-04-18 23:05
Huh, I guess it is enabled:

```
> hs.accessibilityState()
true
```

This is what I see when my I reload my config:

```
2018-04-18 17:02:49: ********
2018-04-18 17:02:49: 17:02:49 ERROR:   LuaSkin: hs.shutdownCallback: attempt to call a nil value
stack traceback:
2018-04-18 17:02:49: ********
2018-04-18 17:02:51: -- Lazy extension loading enabled
2018-04-18 17:02:51: -- Loading ~/.hammerspoon/init.lua
2018-04-18 17:02:51: -- Loading extension: uielement
2018-04-18 17:02:51: THIS PRINTS TO THE CONSOLE
2018-04-18 17:02:51: -- Loading extension: keycodes
2018-04-18 17:02:51: -- Loading extension: eventtap
2018-04-18 17:02:51: -- Done.
```

What else could prevent the keyDown event from firing if accessibility is enabled?

**Comment by latenitefilms** [comment] 2018-04-24 22:10
What happens if you paste the same test code directly in the Console?

**Comment by raineorshine** [comment] 2018-04-25 20:52
```
> print('THIS PRINTS TO THE CONSOLE')

hs.eventtap.new({ hs.eventtap.event.types.keyDown }, function(event)
  print('NEVER CALLED')
end):start()
2018-04-25 14:51:25: THIS PRINTS TO THE CONSOLE
```

No discernibly different behavior.

**Comment by raineorshine** [comment] 2018-04-30 17:51
I'm not sure how to proceed... any other ideas? What else can I troubleshoot if it says accessibility is enabled, but it doesn't behave that way? I am willing to reformat my computer and try installing everything from scratch, but I am hesitant since it is not even guaranteed to get it working.

**Comment by latenitefilms** [comment] 2018-04-30 23:10
Sorry, I'm completely out of ideas - I've certainly never seen this problem on any of our machines.

If you're really keen, you could try reinstalling macOS on an external hard drive and see if that fixes the issue, before you wipe your system?

@asmagill or @cmsj - any other ideas?

**Comment by raineorshine** [comment] 2018-05-01 16:16
@asmagill Thank you for the reply! I wasn't aware I needed to assign the listener to a global variable. That being said, it does not fix the problem. The following code snippet does nothing when I enter it into the console:

```
myEventListener = hs.eventtap.new({ hs.eventtap.event.types.keyDown }, function(event)
  print('NEVER CALLED')
end):start()
```

I think there must be something very aberrant occurring with the Accessibilty.

**Comment by raineorshine** [comment] 2018-05-03 18:01
I am very happy to report that the issue was spontaneously fixed with the latest High Sierra 10.13.4 update. I am unsure whether it was this specific update that mattered, or if any update would have been enough to "reset" the accessibility. My guess is the latter, and the issue was somehow related to restoring my machine via TIme Machine. It is pretty clearly not an issue with Hammerspoon. Hopefully this can help anyone else encountering this problem.

I might suggest adding a note and/or a link to this issue to the FAQ.

Thanks for those who offered ideas and help!

**Comment by raineorshine** [comment] 2018-05-08 23:41
After a restart, the problem returned. I am going to start looking into High Sierra accessibility issues. If anyone has any other tips or ideas, I would welcome them. Thanks!

**Comment by raineorshine** [comment] 2018-05-09 20:04
I still get:

```
2018-05-09 13:55:36: 13:55:36 ERROR:   LuaSkin: hs.eventtap:start() Unable to create eventtap. Is Accessibility enabled?
```

I have confirmed that it is enabled 1) in Hammerspoon preferences, 2) in settings, 3) in sqlite database at /Library/Application\ Support/com.apple.TCC/TCC.db.

I was unable to find any general information about Accessibility that might help get closer to the problem.

**Comment by vjpr** [comment] 2018-11-27 03:50
@raineorshine I just upgraded to Mojave and I'm seeing the same message. Did you solve it?

**Comment by raineorshine** [comment] 2018-11-27 03:56
@vjpr No, I hit a dead-end. I have been using an alternative to Hammerspoon for my specific use case since then.

**Comment by vjpr** [comment] 2018-11-27 04:05
Fixed it. I re-added my app to `system preferences -> security -> privacy -> accessibility`.

---

This thread may also be useful if problem persists: [CGEventTapCreate fail on Mojave (10.14)](https://forums.developer.apple.com/thread/109283).

**Comment by MynockSpit** [comment] 2019-06-18 23:28
Having the same issue... but only on one of my two Mojave machines. The other works fine. Interestingly enough, this works: 

```lua
hs.osascript.applescript('tell application "System Events" to key code 100 using {command down, option down, shift down, control down}')
```

But this doesn't:

```lua
hs.eventtap.keyStroke({"ctrl", "alt", "cmd", "shift"}, "f8", pressTimeMs)
```

It's not a great solution (it's a lot less responsive), but it works.

**Comment by viddo** [comment] 2019-11-18 17:51
I encountered the same issue as the original poster.  In my case, the same script works on one of my Macbooks (13" late 2013 model), but fails on the other (15" 2018 model). Confirmed accessibility is enabled on both. Both machines are running latest version of Catalina (10.15.1 (19B88) at time of writing).

One observation I'm seeing when fiddling in the console is that some other types works where as keyDown/keyUp does not, e.g.:
```
-- this works!
hs.eventtap.new({ hs.eventtap.event.types.flagsChanged }, function(event)
  print('flagsChanged called')
end):start()
```
```
-- these does not work
hs.eventtap.new({ hs.eventtap.event.types.keyDown }, function(event)
  print('keyDown is never called')
end):start()
hs.eventtap.new({ hs.eventtap.event.types.keyUp }, function(event)
  print('keyUp is never called')
end):start()
```

**Comment by viddo** [comment] 2019-11-18 21:25
I just noticed that after unplugging the computer from external screens it started working, and plugging back it still works now. Is there something with external displays/ports that somehow could cause this? 🤔

**Comment by jackcasey** [comment] 2020-04-08 06:42
I just started getting this randomly today. Working this morning not this afternoon. Catalina. Other things work but `eventtap` on `keyDown` doesn't. Tried most of the the suggestions on this page. including running tccutil reset All org.hammerspoon.Hammerspoon
` in terminal. Will try a few more things.

**Comment by jackcasey** [comment] 2020-04-08 07:13
Just came back to my computer after leaving it for about 10 minutes and it 'woke up' and now it's all working fine, didn't even restart hammerspoon. Definitely something to do with MacOS not passing along events. Could well be related to external monitors. 🤷‍♂

**Comment by virtualirfan** [comment] 2020-05-13 20:50
Fwiw, 

```sh
osascript -e 'tell Application "Hammerspoon" to quit'
tccutil reset All org.hammerspoon.Hammerspoon
```

followed by dragging in the Hammerspoon.app file from Finder into the Privacy/Accessibility window seems to have worked for me.

**Comment by viddo** [comment] 2020-05-20 16:55
Happened today again after waking up computer this morning (put it to sleep last night). Took a screenshot of the test I mentioned above:
<img width="684" alt="Screen Shot 2020-05-20 at 08 44 58" src="https://user-images.githubusercontent.com/978461/82471434-8a4a4700-9a7b-11ea-92d1-be5647298019.png">
As can be seen flags events (alt, cmd etc.) are identified, keyDown/keyUp events are not.

Tried resetting accessibility using `tccutil reset` in this thread has not worked either. However, after trying a few combination of things this appears to make it work again:
- Unplug external display
- Quit Hammerspoon
- Remove accessibility permission for Hammerspoon in privacy preferences
- Put computer to sleep
- Wake up computer
- Add accessibility privileges for Hammerspoon in privacy preferences
- Start Hammerspoon
![Screen Shot 2020-05-20 at 09 38 51](https://user-images.githubusercontent.com/978461/82472970-c2528980-9a7d-11ea-8173-6f6025aa8f49.png)

Unplugging of the display and sleep/wake up sequence appeared necessary to make it work again ¯\\\_(ツ)\_/¯

**Comment by asmagill** [comment] 2020-05-22 17:20
Well, in the latest example `keyUp` events *wouldn't* be caught because they're not specified.

If you don't capture the eventtap in a global variable or upvalue-captured local, then they will get cleared when lua garbage collection occurs... exactly how often this occurs depends upon how much lua/Hammerspoon activity you going on in the background, but we can force it with `collectgarbage()`:

Some of the examples above capture the eventtap, some don't, so I apologize if this demonstration is unnecessary, but just to be clear:


Not assigned to global variable / upvalue-captured local:

~~~lua
> hs.eventtap.new({ hs.eventtap.event.types.keyDown }, function(event) print('Key Down') end):start()
hs.eventtap: Eventtap Mask: 0x400 (0x60700018bd18)
2020-05-22 11:59:00: Key Down -- cut and pasted the next line, so just a few actual keyDown events occurred
2020-05-22 11:59:10: Key Down
2020-05-22 11:59:12: Key Down
2020-05-22 11:59:14: Key Down
2020-05-22 11:59:17: Key Down

> hs.eventtap.new({ hs.eventtap.event.types.flagsChanged }, function(event) print('Flags Changed') end):start()
hs.eventtap: Eventtap Mask: 0x1000 (0x60700009ce38)
2020-05-22 11:59:19: Flags Changed
2020-05-22 11:59:19: Flags Changed -- went to sleep after this
2020-05-22 11:59:44: Flags Changed -- woke up
2020-05-22 11:59:44: Flags Changed
2020-05-22 11:59:48: Flags Changed
2020-05-22 11:59:48: Flags Changed
2020-05-22 11:59:48: Flags Changed
2020-05-22 11:59:48: Key Down
2020-05-22 11:59:49: Flags Changed
2020-05-22 11:59:49: Flags Changed
2020-05-22 11:59:49: Flags Changed
2020-05-22 11:59:52: Key Down
2020-05-22 11:59:53: Key Down
2020-05-22 11:59:53: Key Down
2020-05-22 11:59:53: Key Down
2020-05-22 11:59:53: Key Down
2020-05-22 11:59:53: Key Down
2020-05-22 11:59:54: Key Down
2020-05-22 11:59:54: Key Down
2020-05-22 11:59:54: Key Down
2020-05-22 11:59:55: Key Down
2020-05-22 11:59:55: Key Down
2020-05-22 11:59:55: Key Down
2020-05-22 11:59:55: Key Down
2020-05-22 11:59:55: Key Down
2020-05-22 11:59:55: Flags Changed
2020-05-22 11:59:55: Key Down
2020-05-22 11:59:55: Key Down
2020-05-22 11:59:56: Flags Changed
2020-05-22 11:59:56: Key Down

> collectgarbage() -- force gc and notice that no keys/flags are captured for the next one
0

> collectgarbage()
0
~~~

And now with a global capture of the eventtap:


~~~lua
> k = hs.eventtap.new({ hs.eventtap.event.types.keyDown }, function(event) print('Key Down') end):start()

2020-05-22 12:01:23: Key Down -- used up arrow to go back so a few keydowns here
2020-05-22 12:01:24: Key Down
2020-05-22 12:01:25: Key Down
2020-05-22 12:01:25: Key Down
2020-05-22 12:01:26: Key Down
2020-05-22 12:01:28: Key Down
2020-05-22 12:01:29: Key Down
2020-05-22 12:01:29: Key Down
2020-05-22 12:01:29: Key Down
2020-05-22 12:01:30: Key Down
2020-05-22 12:01:30: Key Down

> f = hs.eventtap.new({ hs.eventtap.event.types.flagsChanged }, function(event) print('Flags Changed') end):start()

2020-05-22 12:01:35: Key Down
2020-05-22 12:01:35: Key Down
2020-05-22 12:01:35: Key Down
2020-05-22 12:01:35: Key Down
2020-05-22 12:01:35: Key Down
2020-05-22 12:01:35: Key Down
2020-05-22 12:01:36: Key Down
2020-05-22 12:01:36: Key Down
2020-05-22 12:01:36: Key Down
2020-05-22 12:01:36: Key Down
2020-05-22 12:01:36: Key Down
2020-05-22 12:01:37: Key Down
2020-05-22 12:01:37: Key Down
2020-05-22 12:01:37: Key Down
2020-05-22 12:01:37: Flags Changed
2020-05-22 12:01:37: Key Down
2020-05-22 12:01:37: Key Down
2020-05-22 12:01:37: Flags Changed
2020-05-22 12:01:38: Key Down

> collectgarbage()
0
2020-05-22 12:01:39: Key Down -- eventtaps still in place
2020-05-22 12:01:39: Key Down
2020-05-22 12:01:39: Key Down
2020-05-22 12:01:39: Key Down
2020-05-22 12:01:39: Key Down
2020-05-22 12:01:39: Key Down
2020-05-22 12:01:40: Key Down
2020-05-22 12:01:40: Key Down
2020-05-22 12:01:40: Key Down
2020-05-22 12:01:40: Key Down
2020-05-22 12:01:40: Key Down
2020-05-22 12:01:40: Key Down
2020-05-22 12:01:40: Key Down
2020-05-22 12:01:41: Key Down
2020-05-22 12:01:41: Flags Changed
2020-05-22 12:01:41: Key Down
2020-05-22 12:01:41: Key Down
2020-05-22 12:01:41: Flags Changed
2020-05-22 12:01:42: Key Down

> collectgarbage()
0
2020-05-22 12:01:42: Key Down
2020-05-22 12:01:43: Flags Changed
2020-05-22 12:01:43: Key Down
2020-05-22 12:01:43: Flags Changed
2020-05-22 12:01:43: Key Down
2020-05-22 12:01:43: Key Down
2020-05-22 12:01:43: Key Down
2020-05-22 12:01:43: Key Down
2020-05-22 12:01:43: Flags Changed
2020-05-22 12:01:44: Key Down
2020-05-22 12:01:44: Key Down
2020-05-22 12:01:44: Flags Changed
2020-05-22 12:01:44: Key Down

> k:stop() -- until we actually stop them
hs.eventtap: Eventtap Mask: 0x400 (0x607000203f78)
2020-05-22 12:01:45: Flags Changed 
2020-05-22 12:01:46: Flags Changed
2020-05-22 12:01:47: Flags Changed
2020-05-22 12:01:47: Flags Changed

> f:stop()
hs.eventtap: Eventtap Mask: 0x1000 (0x607000213638)

> 
~~~


I also checked setting the eventtaps if accessibility is actually disabled... aside from being notified by Hammerspoon of this when it starts, trying to setup an eventtap results in:

~~~lua
2020-05-22 12:10:22: -- Loading extension: eventtap
2020-05-22 12:10:22: ********
2020-05-22 12:10:22: 12:10:22 ERROR:   LuaSkin: hs.eventtap:start() Unable to create eventtap. Is Accessibility enabled?
2020-05-22 12:10:22: ********
~~~

I have noticed that some apps have a "Secure Keyboard Entry" option (Terminal has this in its application menu) and if this is enabled, then when that particular app is active, key events don't get propagated though flag changes do. However, this shouldn't affect the capture of keyUp/Down events if the Hammerspoon console itself is the active window. 

I'll repeat your closing line: ¯\_(ツ)_/¯

**Comment by raineorshine** [comment] 2020-05-22 17:43
@asmagill Good clarification. 

Just so nobody gets the wrong idea, the problem [still occurs with a global capture](https://github.com/Hammerspoon/hammerspoon/issues/1743#issuecomment-385712733).

**Comment by asmagill** [comment] 2020-05-22 18:02
Ok, according to this link, Secure Keyboard Entry enabled in any app, foreground *or* background will prevent keyUp/keyDown events from being captured from any app not running as root (we don’t).

https://security.stackexchange.com/questions/47749/how-secure-is-secure-keyboard-entry-in-mac-os-xs-terminal#47786

I won’t be at my mac for a couple of hours to verify this, but it might be worth checking if you have this enabled in Terminal or another application. From my experience, password managers are good about only enabling it when dealing with passwords and then disabling it when not needed anymore, but other apps might not be written as well.

**Comment by raineorshine** [comment] 2020-05-22 19:51
FYI I switched to another solution last year so I hadn't tested this in a while, but when I try it now (OSX Mojave 10.14.6) it works.

¯\_(ツ)_/¯

**Comment by asmagill** [comment] 2020-05-22 19:53
Nope, enabling Secure Keyboard Entry in Terminal only seems to block keyUp/Down within Terminal itself... when something else is frontmost, it works:

~~~lua
> k = hs.eventtap.new({ hs.eventtap.event.types.keyDown }, function(event) print(hs.application.frontmostApplication():title() .. ': Key Down') end):start()
f = hs.eventtap.new({ hs.eventtap.event.types.flagsChanged }, function(event) print(hs.application.frontmostApplication():title() .. ': Flags Changed') end):start()


Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Flags Changed
Hammerspoon: Flags Changed
Safari: Flags Changed
Safari: Flags Changed
Safari: Key Down
Safari: Key Down
Terminal: Key Down
Terminal: Key Down
Terminal: Key Down
Terminal: Key Down
Terminal: Key Down -- I switched Secure Keyboard Entry on at this point
Terminal: Flags Changed
Terminal: Flags Changed
Terminal: Flags Changed
Terminal: Flags Changed
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
Safari: Key Down
BBEdit: Flags Changed
BBEdit: Flags Changed
BBEdit: Flags Changed
BBEdit: Key Down
Hammerspoon: Flags Changed
Hammerspoon: Flags Changed
Hammerspoon: Flags Changed
BBEdit: Flags Changed
BBEdit: Flags Changed
BBEdit: Flags Changed
BBEdit: Key Down
BBEdit: Flags Changed
BBEdit: Flags Changed
BBEdit: Key Down
BBEdit: Key Down
BBEdit: Flags Changed
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Flags Changed
Hammerspoon: Key Down
Hammerspoon: Flags Changed
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Flags Changed
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Flags Changed
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Flags Changed
Hammerspoon: Key Down
Hammerspoon: Flags Changed
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Flags Changed
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Flags Changed
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down
Hammerspoon: Key Down

> f:stop(), k:stop()
hs.eventtap: Eventtap Mask: 0x1000 (0x60700002cab8)	hs.eventtap: Eventtap Mask: 0x400 (0x60700142b3a8)

> 

~~~

So... unless there is a global Secure Keyboard Entry toggle somewhere? Back to ¯\\\_(ツ)\_/¯

**Comment by asmagill** [comment] 2020-05-22 19:54
And FWIW, I'm running Catalina 10.15.4

**Comment by viddo** [comment] 2020-05-28 02:07
> @asmagill Good clarification.
> 
> Just so nobody gets the wrong idea, the problem [still occurs with a global capture](https://github.com/Hammerspoon/hammerspoon/issues/1743#issuecomment-385712733).

My bad! I should have used global capture in my examples so we would not have spun on that detail. Even when using global capture in console still don't register.

> Ok, according to this link, Secure Keyboard Entry enabled in any app, foreground _or_ background will prevent keyUp/keyDown events from being captured from any app not running as root (we don’t).
> 
> https://security.stackexchange.com/questions/47749/how-secure-is-secure-keyboard-entry-in-mac-os-xs-terminal#47786
> 
> I won’t be at my mac for a couple of hours to verify this, but it might be worth checking if you have this enabled in Terminal or another application. From my experience, password managers are good about only enabling it when dealing with passwords and then disabling it when not needed anymore, but other apps might not be written as well.

Oh I think you might be on to something! I found this question when reading up on the topic: https://apple.stackexchange.com/questions/331557/is-there-a-way-to-fix-or-disable-secure-input
I had the issue just now again so could try some things: Turning on screensaver (which forces me to enter password/touch id to enter again) and logging in again did resolve the issue this time. So I wonder if there is some issue with wake up + login using the touch id that doesn't properly disable the secure keyboard intro from the loginwindow, perhaps? I figure that might explain why this is only observed on some occasions and when waking up the computer specifically.

**Comment by jackcasey** [comment] 2020-06-11 00:49
I have noticed the same things as others around screensave / system locking.

As an interesting bit of evidence; I have BetterTouchTool installed which has a system tray icon. And in the dropdown menu for the tray icon it will show an indication if something is enabling secure input (because it breaks some BTT features, just like it breaks event tap). So it's a nice diagnostic.

For example here it is showing that the 1Password password entry form is enabling secure input. 
![Screen Shot 2020-06-11 at 8 43 44 am](https://user-images.githubusercontent.com/45890/84332570-d6426480-abbf-11ea-87ce-332275ff36a8.png)
(This goes away when I defocus the dialog). 

In the case where the whole system is enabling secure input it was showing that some OSX system "Login" or "Lock" was enabling the secure input. (Sorry I don't have a screenshot of this) Re-locking the machine and unlocking it again cleared this 'flag' and event tap started working again.

So it appears to be that the MacOS lock widget etc has some sort of issue where even when dismissed it keeps secure input enabled system wide. I wonder if there is a timing issue, like if the screensaver comes on but you wake the computer up before the lock kicks in it sort of 'soft' kicks in and enables secure input but doesn't ask you to re-log in (because not enough time elapsed) and then gets stuck. Just a theory.

**Comment by asmagill** [comment] 2020-06-11 01:16
~~I was actually wondering the other day if we might be able to detect secure input status... it's nice to see that BTT shows that it *is* possible... now we just need to figure out how.~~

Apparently someone already beat me to it, see `hs.eventtap.isSecureInputEnabled`... but this doesn't tell us *which* app has enabled it... I wonder how BTT is doing that... I won't have time to research this for a little bit (I'm trying to finish up a couple of modules that we want in the next release of Hammerspoon), but I'll keep it on my list.

Of course if anyone has any suggestions or insights, please post here or submit a pull request yourself!

**Comment by latenitefilms** [comment] 2020-06-11 04:01
I believe you can use this to find out which app has Secure Input:

```
ioreg -l -w 0 | grep SecureInput
```

**Comment by giuliano108** [comment] 2021-05-12 14:02
> I had the issue just now again so could try some things: Turning on screensaver (which forces me to enter password/touch id to enter again) and logging in again did resolve the issue this time. So I wonder if there is some issue with wake up + login using the touch id that doesn't properly disable the secure keyboard intro from the loginwindow, perhaps? I figure that might explain why this is only observed on some occasions and when waking up the computer specifically.

Just to further confirm what @viddo said:

* eventtap is not working, `loginwindow` (pid 178) enabled secure input:

```
$ ioreg -l -w 0 | grep SecureInput
  |   "IOConsoleUsers" = ({"kCGSSessionOnConsoleKey"=Yes,"kCGSessionLoginDoneKey"=Yes,"kSCSecuritySessionID"=100006,"kCGSSessionSecureInputPID"=178,"kCGSSessionSystemSafeBoot"=No,"kCGSSessionUserNameKey"="gcioffi","kCGSSessionIDKey"=257,"kCGSSessionGroupI
    | |   "IOConsoleUsers" = ({"kCGSSessionOnConsoleKey"=Yes,"kCGSessionLoginDoneKey"=Yes,"kSCSecuritySessionID"=100006,"kCGSSessionSecureInputPID"=178,"kCGSSessionSystemSafeBoot"=No,"kCGSSessionUserNameKey"="gcioffi","kCGSSessionIDKey"=257,"kCGSSessionGr
$
$ ps axo pid,command | grep 178
  178 /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow console
$
```

* I lock my screen again, unlock it via the fingerprint scanner. This time, secure input gets disabled and eventtap works as it should: 

```
$ ioreg -l -w 0 | grep SecureInput
$
```

**Comment by quickdraw6906** [comment] 2021-06-27 20:02
I have this issue as well. The solution (may be temporary...stay tuned) was to take the PID from the `ioreg` command and kill it. I got bounced to the login screen and logged in and things work again.

**Comment by vjpr** [comment] 2021-06-27 21:44
Maybe a other event tap conflicts. You can use osquery tool to view all
registered event taps.

**Comment by giuliano108** [comment] 2024-07-22 18:53
The issue cropped up again today, but the workaround described in my previous (2021) comment didn't fix. Killing the PID from `ioreg` (as per quickdraw6906's) works only temporarily.

The permanent fix was dragging `Hammerspoon.app` into `Privacy & Security` → `Input Monitoring`.

**Comment by cmsj** [comment] 2024-08-06 09:59
I think this issue has existed for long enough and been through enough forms that it probably should just be closed!

**Closed** 2024-08-06 09:59 UTC
Labels: needs-response
