### ISSUE TITLE
The merge of #2466 has broken HS

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#2467] opened 2020-09-18 20:54 UTC
I'm on 10.14.6, and just built HS afresh.  Upon opening Hammerspoon, I see:

```
2020-09-18 16:49:52: -- Loading extension: hotkey
2020-09-18 16:49:52: *** ERROR: ...oon.app/Contents/Resources/extensions/hs/logger/init.lua:185: attempt to call a nil value (upvalue 'printf')
stack traceback:
	...oon.app/Contents/Resources/extensions/hs/logger/init.lua:185: in function <...oon.app/Contents/Resources/extensions/hs/logger/init.lua:173>
	(...tail calls...)
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:72: in function <...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:54>
	(...tail calls...)
	/Users/chdiza/.rc/hs/init.lua:4: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:695: in function 'hs._coresetup.setup'
	(...tail calls...)
```

This wasn't present last time I built HS, which was 4e793ec8021ab.

**Comment by asmagill** [comment] 2020-09-19 03:01
I am unable to reproduce this and I've been running the new codebase since it was merged... in the console, if you type `hs.printf` does it return something like `function: 0x6040000beb90`?

The changes in the latest pull should have no effect on this from what I can see and have observed on my machine.

Is `/Users/chdiza/.rc/hs/init.lua` available somewhere to be viewed online to see if something in there (or something it's loading) is affecting the definition of `hs.printf`?  If not, could you share the first few lines (including whatever line or function is defined at line 4)...

**Comment by latenitefilms** [comment] 2020-09-19 03:10
Ummm, I can't reproduce this either when using the code from the `master` branch.

#2466 is pretty basic in that it only declares `hs.host` and `hs.timer` earlier in the Lua code, and because @chdiza's `init.lua` code won't be triggered until the very end of `_coresetup/init.lua`, I don't see how this could have any impact on anything.

The only thing I can think of trying is moving `hs.coroutineApplicationYield` and `local host = require("hs.host"); local timer = require("hs.timer")` to later in `_coresetup/init.lua` - but again, I'm not really sure why this would be needed.

I'll try merging these changes into CommandPost too, and see if that offers any further clues.

**Comment by latenitefilms** [comment] 2020-09-19 03:51
FWIW - the merge also doesn't break CommandPost.

**Comment by chdiza** [comment] 2020-09-19 04:48
@asmagill Here are the first four lines of ~/.rc/hs/init.lua:

```lua
require "hs.ipc" --for some reason this can't be deleted, but don't know why; possibly cruft.
local frontmostWindow = hs.window.frontmostWindow()
bam = {"cmd","ctrl","alt"}
hs.hotkey.bind(bam, "F9",  function() hs.openConsole() end)
```

If in the HS console I type `hs.printf`, I get: `function: 0x60000386aa90`

**Comment by chdiza** [comment] 2020-09-19 04:51
If I comment out the entire ~/.rc/hs/init.lua except for the fourth line, I still get the exact same console output.

**Comment by chdiza** [comment] 2020-09-19 04:57
Possibly it's because my MJConfigFile is set in the HS preference plist to "/users/chdiza/.hs/init.lua"; the ".hs" is a symlink to "$HOME/.rc/hs", and I see that the 2466 has done something invovling links and paths.

Welp, no, that's perhaps not it because I just experimented by pointing MJConfigFile at the target rather than at the symlink, and the same error messages appear.

**Comment by asmagill** [comment] 2020-09-19 05:10
When you say that you commented out the entire contents of `init.lua`, did that include the `require "hs.ipc"` line? `hs.ipc` has to be loaded for the external shell command `hs` to work, and it does swap out `print` for it's own version, but I don't think it touches `hs.printf` at all... I'll look at it closer in a few minutes and try your config as described above as well.

Have you confirmed that reverting the latest pull and rebuilding Hammerspoon does in fact make it work again?

**Comment by chdiza** [comment] 2020-09-19 05:14
4e793ec8021ab37656 is the thing that has a change regarding paths and symlinks.  But I manually reverted that one (while leaving the rest of #2466 the same) and it didn't help anything.

I've flipped back and forth between #2466 and the previous state, and I can reproduce the error every time.

> When you say that you commented out the entire contents of init.lua, did that include the require "hs.ipc" line?

@asmagill Yes, that's what I meant.  I tried it again while commenting out everything *but* that require and line 4, with the same result.

I don't know if it matters, but I always launch HS via the `hs` command.

**Comment by asmagill** [comment] 2020-09-19 05:22
Sorry to be nitpicky, but I just want to be certain... you've actually recompiled without the latest pull, not just running a saved binary from a previous build, correct?

And the starting from the command line... I don't *think* it should matter, since the app is still being launched through the macOS Application Services (or whatever it's called today), but it could slightly alter the load order of some internal things... can't currently see how that should affect the loading of the core lua files, though, but I'll look into it.

**Comment by asmagill** [comment] 2020-09-19 05:45
Oh, and just to clarify, #2464, #2463, and #2457  modified some path resolvers in `hs.fs`, `hs.pathwatcher`, and `hs.doc`... #2466 only modifies `hs._coresetup` to reduce log spamming when `coroutine.applicationYield` is used.

if it's the path resolving changes (though I *think* they are too high level to be causing this) then your previous build was likely older than you originally thought.

**Comment by asmagill** [comment] 2020-09-19 05:56
I think I've mimicked your setup as closely as possible and still don't see the issue. Here's what I've done, so let me know if you think I've missed something:

~~~sh
$ cd
$ mkdir .rc
$ cd .rc
$ mkdir hammerspoonForReal
$ ln -s hammerspoonForReal hs
$ vi hs/init.lua # and copy/pasted the 4 line `init.lua` you give above)
$ # quite running Hamerspoon, if it's running
$ defaults write org.hammerspoon.Hammerspoon MJConfigFile "~/.rc/hs/init.lua"
$ hs -A -C # I've also tried it with no arguments, and also without -C -- no difference
Hammerspoon interactive prompt.

> 
~~~

and `Cmd-Alt-Ctrl F9` brings up the console as expected with no extraneous messages or errors displayed.

I'm at a loss, unless maybe you have some other changes to the core HS code that you're testing out as well? Do you have an `hs` directory in your config directory with modules that overrides any of the core modules (a trick I sometimes use when testing out changes but don't want to have to recompile the whole thing)?

**Comment by asmagill** [comment] 2020-09-19 06:15
NVM... I was running the above test with a branch copy that didn't have the last pull added... now when I run my stock setup it works, but when I run the commands I outlined above, I get your error...

Which is really really odd, but at least I can investigate now that I can recreate it... more to follow.

**Comment by asmagill** [comment] 2020-09-19 07:01
Ok, not sure of the "cleanest" fix yet, but I know what's happening...

`hs.timer` requires `hs.logger` and `hs.logger` sets a local value `printf` to `hs.printf` at the begining and uses it as an upvalue everywhere else, but since we're explicitly loading the timer module before `hs.printf` is defined, `printf` is set to `nil`. My config worked because I set the default log level for `hotkey` to "warning" before I define any hotkeys to reduce console spamming. But when I try to run `hs.logger.printHistory()`, I get the same `printf` is nil error... @latenitefilms I'll bet you will too, if you try it.

The simplest fix is going to be moving the definition of `hs.printf` to somewhere before the requiring of `hs.host` and `hs.timer` (host requires timer as well), but the `_coresetup` init file makes some somewhat not-immediately-obvious assumptions about the order of things, so I need to think this through to be safe and not inadvertently break something else because of the change in ordering...

The other option is to change `hs.logger` so it doesn't use upvalues for any of the Hammerspoon specific additions so definition order no longer matters... but that gets into the arena of imposing programming styles and the question of speed gains for global vs upvalue lookups and that's a whole flame-war-waiting-to-happen that I'd rather avoid.

So, let me play with `_coresetup` for a bit and see what I can come up with.

**Comment by latenitefilms** [comment] 2020-09-19 07:26
A possible easy (untested) fix?

```lua
local host, timer
hs.coroutineApplicationYield = function(delay)
    if not host then host = require("hs.host") end
    if not timer then timer = require("hs.timer") end
    delay = delay or hsmath.minFloat

    local thread, isMain = coroutine.running()
    if not isMain then
        local uuid = host.uuid()
        resumeTimers[uuid] = timer.doAfter(delay, function()
            resumeTimers[uuid] = nil
            local status, msg = coroutine.resume(thread)
            if not status then
                hs.luaSkinLog.ef("hs.coroutineApplicationYield: %s", msg)
            end
        end)
        coroutine.yield()
    else
        error("attempt to yield from outside a coroutine", 2)
    end
end

coroutine.applicationYield = hs.coroutineApplicationYield
```

**Comment by asmagill** [comment] 2020-09-19 07:29
Ahh, I was trying to think how to mimic static within lua... that would work if you add `local host, timer` outside of the function.  However, I'm testing a pull where I've moved a couple of things around that I think is cleaner anyways.

**Closed** 2020-09-19 08:20 UTC

**Comment by asmagill** [comment] 2020-09-19 08:24
@chdiza reopen if the latest merge doesn't fix things for you.

**Comment by chdiza** [comment] 2020-09-19 13:21
I can confirm that the problem has disappeared.  Thanks so much!
