### ISSUE TITLE
Problem about update a menubar item

### ISSUE THREAD

**Issue by hououinkami** [Hammerspoon/hammerspoon#2091] opened 2019-05-04 16:05 UTC
Hi!
I updated Hammerspoon from 0.9.73 to 0.9.75. Then I found the hs.menubar didn't function as before. I make a menubar item with title and menu, and update it by hs.timer.doAfter(1, fn), that is, it's deleted and remade every second.
But when I clicked the menubar item and saw the menu shown, all items of the menu disappeared with the menu frame remained after one second.
How do I fix this problem? 
Thanks very much!

**Comment by latenitefilms** [comment] 2019-05-06 11:36
Ummmm... AFAIK nothing in `hs.menubar` has really changed between 0.9.73 and 0.9.75, so I wonder if something has changed in a recent macOS update?

I can reproduce the problem you're having using this code:

```lua
mb = hs.menubar.new()
	:setTitle("Test")
	:setMenu({
       { title = "my menu item", fn = function() print("you clicked my menu item!") end },
       { title = "-" },
       { title = "other item", fn = some_function },
       { title = "disabled item", disabled = true },
       { title = "checked item", checked = true },
   })
   
tm = hs.timer.doEvery(1, function()
	print("Updating Menubar")
	mb:setMenu({
       { title = "my menu item", fn = function() print("you clicked my menu item!") end },
       { title = "-" },
       { title = "other item", fn = some_function },
       { title = "disabled item", disabled = true },
       { title = "checked item", checked = true },
	})	
end)
```

However, rather than updating every 1 second, why not just update whenever you click the menubar icon? For example:

```lua
mb = hs.menubar.new()
	:setTitle("Test")
	:setMenu(function()
		print("Menu bar updating...")
		return {
		   { title = "my menu item", fn = function() print("you clicked my menu item!") end },
		   { title = "-" },
		   { title = "other item", fn = some_function },
		   { title = "disabled item", disabled = true },
		   { title = "checked item", checked = true },
	   }
   end)
```

**Comment by latenitefilms** [comment] 2019-05-06 11:38
Maybe related: https://github.com/Hammerspoon/hammerspoon/issues/1923

**Comment by hououinkami** [comment] 2019-05-06 12:27
Thanks for your reply!
I used it to show the title and artist of iTunes's current track, so I needed to update the menubar item every second no matter I clicked it or not.Is this possible?

**Comment by latenitefilms** [comment] 2019-05-06 12:34
Sorry, I'm a little confused. Do you just want the menubar title to just update every second? If so, this seems to work fine for me?

```lua
mb = hs.menubar.new()
	:setTitle("Loading...")
   
tm = hs.timer.doEvery(1, function()
	print("Updating Menubar")
	mb:setTitle(os.time())
end)
```

You could update the title every second, then if you are actually using a menu as well, you could update the menu whenever it's clicked?

For example:

```lua
mb = hs.menubar.new()
	:setTitle("Test")
	:setMenu({
       { title = "my menu item", fn = function() print("you clicked my menu item!") end },
       { title = "-" },
       { title = "other item", fn = some_function },
       { title = "disabled item", disabled = true },
       { title = "checked item", checked = true },
   })
   
tm = hs.timer.doEvery(1, function()
	print("Updating Menubar")
	mb:setTitle(os.time())
end)
```

**Comment by hououinkami** [comment] 2019-05-07 02:01
Thanks for your sample code!
Yes, I just want the menubar title to update every second, but I want the menu(show the rating and other information of current track) to update every second. The sample code seems to work only for updating the menubar title.

**Comment by latenitefilms** [comment] 2019-05-25 07:07
I can confirm this issue, with the following code:

```lua
mb = hs.menubar.new()
	:setTitle(string.format("The time is: %s", os.time()))
	:setMenu({
       { title = string.format("The time is: %s", os.time()) },
   })
   
tm = hs.timer.doEvery(1, function()
	print("Updating Menubar")
	mb:setTitle(os.time())
	mb:setMenu({
       { title = string.format("The time is: %s", os.time()) },
   })
end)
```

This bug seems to be a duplicate of #1923 - so you may want to close this issue @asmagill or @cmsj in favour of #1923.

**Comment by cmsj** [comment] 2019-08-15 21:44
Closing, since it's a duplicate. Thanks all!

**Closed by cmsj** 2019-08-15 21:44 UTC
