### ISSUE TITLE
New hs CLI crash when using "-A" flag

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#1490] opened 2017-07-17 19:47 UTC
I tested out the new autolaunch capability of `hs` by using the the "-A" flag.  It resulted in a crash:
```
hs -A -c "Generator()"

-- Loading extension: styledtext
2017-07-17 15:41:36.510 hs[67464:831426] *** Terminating app due to uncaught exception 'NSDestinationInvalidException', reason: '*** -[HSClient performSelector:onThread:withObject:waitUntilDone:modes:]: target thread exited while waiting for the perform'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9770c57b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffac9501da objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff97789c55 +[NSException raise:format:] + 197
	3   Foundation                          0x00007fff990c3de2 -[NSObject(NSThreadPerformAdditions) performSelector:onThread:withObject:waitUntilDone:modes:] + 1042
	4   Foundation                          0x00007fff99144837 -[NSObject(NSThreadPerformAdditions) performSelector:onThread:withObject:waitUntilDone:] + 119
	5   hs                                  0x00000001006cc064 main + 10148
	6   libdyld.dylib                       0x00007fffad231235 start + 1
	7   ???                                 0x0000000000000004 0x0 + 4
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

I also tried the semi-autolaunch capability (where one is prompted whether to launch hammerspoon), and that did *not* crash.

BTW, I'm sorry I'm only testing this stuff out now.  My git skills are exceptionally weak and I don't know how to branch locally and get WIP PRs on my machine in order to test.  Not that I had the time anyway.

**Comment by asmagill** [comment] 2017-07-17 21:38
What does your "Generator" function do?

The following works properly on my system:

~~~sh
$  hs -A -c "hs.inspect(hs, { depth = 1 })"
-- Loading extension: inspect{
  _consoleInputPreparser = <function 1>,
  _exit = <function 2>,

// truncated for brevity
 
  uploadCrashData = <function 34>,
  window = {...}
}
$
~~~

**Comment by chdiza** [comment] 2017-07-17 21:43
> What does your "Generator" function do?

It activates my fake GeekTool apparatus.  This involves, among many other things, starting timers and hs.tasks.

**Comment by chdiza** [comment] 2017-07-17 21:45
I have discovered that the crash doesn't happen every single time.

**Comment by asmagill** [comment] 2017-07-17 21:47
Probably a timing thing then... try setting the timeout with `-t` and I'll look closer at the launch detection code to see if it can be made more flexible.

**Comment by asmagill** [comment] 2017-07-18 02:49
I am not able to make `hs` crash during a forced autoload... I've placed delays at various points that would delay the port being created in time, between port creation and being ready for command execution, and with a command that exceeds the execution timeouts... for each I get an expected behavior (case 1: failure to connect and exit, case 2: fallback to legacy mode then exit with "timeout", case 3: exit with regular timeout) but never a crash.

Can you check to see if there is a crash log file for hs and post it?  It would be in `~/Library/Logs/DiagnosticReports/` and be named something like `hs_<date-time>_<host>.crash`... feel free to blot out any details (paths, hostname, etc) that you feel might compromise privacy.

Is your full config hosted somewhere? Looking at the order in which things load may suggest other things I can take a closer look at or build tests for.

**Comment by chdiza** [comment] 2017-07-18 04:53
Crash log [here](https://gist.github.com/chdiza/964378106eda24952a9dcd0276d2ea92).

My config isn't hosted anywhere, and ideally I'd like to keep it that way.  But if I keep getting crashes, I'll think about posting it.

I haven't been able to reproduce the crash for several hours, though I have been trying.

**Comment by asmagill** [comment] 2017-07-18 05:42
The crash log confirms what I was beginning to suspect was happening but don't know how to predictably replicate... 

To make the command line tool able to receive output asynchronously from Hammerspoon (for console replication, proper separation of stdout and stderr for lua errors, etc.), the message port receiver runs in a background thread and has a run loop attached to it.  Your crash occurs during cleanup when the command line tool is getting ready to terminate -- the main thread issues a cancel order to the background thread, but because we're using a runloop, its possible that it may block (in the background thread) for a while before detecting this, so the cancel command is followed immediately with an Objective-C message to the thread (basically a no-op), which causes the runloop to stop blocking and detect that its been cancelled.  About the only way I can think of the thread already detecting the cancel request before the very next message sent from the main thread is if it coincided with the timer on the background run loop to verify that Hammerspoon was still alive... as far as I can tell, the odds of these things lining up just right to cause the crash you saw should be highly improbable... how often have you seen this crash?  And definitely let me know if you start seeing it again.

I need to mull this over for a bit... the only fix I can see at the moment is to wrap the cleanup code in a try/catch block and silently ignore the exception if it occurs... but that's ugly and really doesn't "fix" the problem, just sweeps it under the rug.  In our case the impact is minimal -- the command line client may not get properly unregistered from Hammerspoon, but there is a timer that runs once a minute (I think... I may have changed it to every 5) that looks for stale registrations and purges them automatically, so it's not a big deal, just... ugly. :-)

**Comment by chdiza** [comment] 2017-07-18 06:11
>how often have you seen this crash?

I saw it twice just before I reported it.  Then I left HS alone for a while.  Then I've seen it one more time after that, despite trying to trigger it around 20 more times or so.

Does this actually have anything to do with calling `hs` with the "-A" flag?  Perhaps that was just a coincidence.

**Comment by asmagill** [comment] 2017-07-18 06:49
Even that's more often than I would have expected... 

Should have asked this before, but when the command line tool crash does occur, does your GeekTool apparatus start?  Or does that fail as well?

Were all three an `NSDestinationInvalidException` exception with a traceback log of seven lines like the one you posted above? If so, I can't imagine the `-A` having any effect... all that should do (or if you let it prompt you and then click to launch Hammerspoon) is slow things down a bit since it has to wait for Hammerspoon to launch, load your `init.lua` file, wait until `hs.ipc` is loaded, then wait until HS is done executing your `init.lua` since none of the CLI tool's requests can get answered until HS is idle.

When I reduce the timeouts to force this waiting time to be insufficient, I consistently get error messages about timeouts or a missing CFMessagePort (as one would expect) but I've never seen a crash because of it.

The line where the crash occurred in the log file you provided is at the end of the code during the final cleanup (implying that it succeeded in executing the code or a CFMessage port error occurred)... if `-A` affected this, you *should* also see some error message about a missing port or a communications timeout sent to the terminal.

**Comment by chdiza** [comment] 2017-07-18 13:28
> if -A affected this, you should also see some error message about a missing port or a communications timeout sent to the terminal.

Everything I saw in the terminal was just like the first thing I pasted from the terminal in this thread.  I can't recall whether my fake GeekTool got activated or not.  My terminal might even have been in fullscreen mode at the time, which would've obscured any visual evidence of partial fake GeekTool activation.

**Comment by chdiza** [comment] 2017-07-20 02:37
I just tried compiling on a different machine---El Cap, this time---and on first activating the newly-built HS I got instead of a crash:
```
-- Loading extension: styledtext
error communicating with Hammerspoon: receive timeout
```

**Comment by chdiza** [comment] 2017-07-20 02:38
I've also noticed on El Cap that about half the time I get that "Loaded extension: styledtext" in the *terminal*, which should not be there at all.

**Comment by asmagill** [comment] 2017-07-20 04:23
Try adding `-t 6` (or higher) to the command line arguments to see if it helps with the timeout issue.  If it does, I may increase the default timeout (currently 4 seconds) to something like 6 or 8... the concern with a large timeout is that Hammerspoon may block for up to twice the duration specified, so we don't want it too large except when the user does so on purpose.

WRT to the display of `-- Loading extension: styledtext`, in terminal, this is expected -- all output that is caused by the command line tool, anything which uses "print" (which includes log messages and the print statements from the autoloader -- that hasn't been redone yet), goes to the command line tool's stdout.

I do notice with the new pull, however, that it's not including the terminating newline... I think the fix to suppress extraneous newlines is too aggressive so I'll look into that.

**Comment by chdiza** [comment] 2017-07-20 14:56
The display of `-- Loading extension: styledtext`, however, doesn't happen anymore on Sierra.  Not since I tried your advice in https://github.com/Hammerspoon/hammerspoon/issues/1356#issuecomment-301326801.

**Comment by asmagill** [comment] 2017-08-21 04:43
@chdiza, it's been awhile since I've looked at this... are you still seeing the crashes with the current state of the #1491 pull?

**Comment by chdiza** [comment] 2017-08-21 15:47
Sorry, I didn't know I was supposed to be testing that PR.  I'll see if I can apply the diff manually.  (Git skills very, very weak.)

**Comment by chdiza** [comment] 2017-08-21 20:59
I tried that PR, and I don't seem to see the crashes.  Then again, I haven't seen one since the day of the initial report anyway.

The PR does seem to fix the blank line problem.

**Comment by cmsj** [comment] 2017-09-04 19:35
I'd say let's close this out for now on the basis that #1491 probably fixed it, but please feel free to re-open this issue if you run into this again.

**Closed by cmsj** 2017-09-04 19:35 UTC
