### ISSUE TITLE
seems like a bug: hs.timer.doEvery stop working after thousands of loops

### ISSUE THREAD

**Issue by qiaokang0** [Hammerspoon/hammerspoon#3300] opened 2022-10-24 19:29 UTC
I write a very simple script to print an int with hs.timer.doEvery() func
but I found it always stops after a limited loop number (depends on the function complexity code inside the doEvery)

And it's not a problem about the hammerspoon console window, because at first I write a script to draw a text every 5 seconds on my screen and I found it stoped update after 10 minutes, so I write a much easier one to briefly show this problem.

can anybody help me out? thx~~~

![image](https://user-images.githubusercontent.com/21128031/197609134-94c86df1-c4b7-462e-8bba-47f40dad3734.png)

**Comment by dasmurphy** [comment] 2022-10-26 10:14
The problem is that you should save the timer in a variable that is available globally, so that it does not get lost during garbage collection. If you do not save it, then the garbage collection does throw the timer away when running, since it is not referenced any more. That was also mentioned here #3102

Here should be a solution:

```lua
i = 0

function showWord()
  print(i)
end

timerVar = hs.timer.doEvery(0.01,
  function()
    i = i + 1
    showWord()
  end
)
```

**Comment by Rhys-T** [comment] 2022-10-27 05:31
I've run into issues as a result of this sort of thing often enough that I finally added a garbage collection pass to the very end of my `init.lua`, to make sure that if something is going to break, it does so immediately, while I'm still thinking about the code, rather than whenever garbage collection happens to trigger manually.

```lua
-- If I'm forgetting to save any watchers, timers, etc. into variables,
-- make sure they break as soon as possible.
-- I don't know if wrapping this in `doAfter` is really necessary or not -
-- I'm trying to make sure this runs after _everything_ the config does.
gcTimer = hs.timer.doAfter(0, function()
	gcTimer = nil
	collectgarbage()
	collectgarbage() -- second pass in case any objects were resurrected for finalizers the first time
end)
```

**Comment by cmsj** [comment] 2022-10-30 14:57
Thanks @dasmurphy. I'm going to close this issue, since I believe that answer is the correct one. Also, nice idea @Rhys-T !

**Closed** 2022-10-30 14:57 UTC
