### ISSUE TITLE
hs.timer crashes with almost, but not quite, zero repeat interval

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#1588] opened 2017-10-25 22:53 UTC
The following will crash Hammerspoon with the log showing `A CFRunLoopTimer with an interval of 0 is set to repeat`

~~~lua
g = hs.timer.doEvery(.0000000001, function() print("+") end)
~~~

increase the interval to `.000000001` and it works (and I'm sure I'm not getting anywhere *near* that level of granularity, but at least it doesn't crash)

May affect other `hs.timer` methods that use a repeating timer, though some (all?) of these are lua wrappers to `doEvery`.

Don't know enough about computer floating point representations to know if there is a convenient "smallest interval" constant we can check against or if we should just check to see if the interval is < 1e-09 and accept that as "close enough".

**Comment by latenitefilms** [comment] 2017-10-26 09:31
For what it's worth... I can also reproduce this.

Somewhat unrelated question... is it possible to run `hs.timer` on a different "thread" (beware - I don't really understand the technical stuff I'm saying) - so that a timer that "hangs" won't hold up the rest of Hammerspoon?

**Comment by cmsj** [comment] 2017-11-21 22:24
The NSTimeInterval type used for NSTimer claims only "sub-millisecond" accuracy, so we could refuse anything < 0.00001 and be unlikely to have any complaints IMO.

**Comment by asmagill** [comment] 2017-11-21 22:35
I have enough places where I calculate the interval and don't know it in advance, so I'd rather coerce it to 0.00001 rather than refuse; however, I'm fine with that as the boundary.

**Comment by cmsj** [comment] 2017-11-29 00:24
coercing works for me :)

**Comment by cmsj** [comment] 2017-11-29 00:38
@asmagill doh, missed that you'd self-assigned this. Feel free to replace my commit if you have a better answer (it's late here, I'm overdue for sleeping and might be writing nonsense ;)

**Closed** 2017-11-29 00:37 UTC
Labels: crasher

**Comment by asmagill** [comment] 2017-11-29 02:29
Nah, that's fine... I just wanted to assign it to a list that I can review this weekend to prioritize... since you've already done it, commit it.  The only thing I might have done differently is to log it lower than warn (maybe info or even debug) since it's not generally going to be a difference in time that the user would notice.

**Comment by asmagill** [comment] 2017-11-29 02:30
(that said, it should be logged -- a programmer might be interested -- but just at a level lower then is displayed by default.)
