### ISSUE TITLE
Spontaneous and frequent window unfocus

### ISSUE THREAD

**Issue by unnamed777** [Hammerspoon/hammerspoon#1003] opened 2016-09-27 09:15 UTC
I use lastest version (0.9.47) on Sierra to replace some broken Karabiner hotkeys. After installing I started to notice very frequent window unfocusing without any reason. If I wrote some text in browser, textarea is loosing focus and window becomes inactive (I still see app's name in menubar). If I watch a movie, mouse cursor is showing and hiding spontaneously. When I clean my init.lua (http://pastebin.com/s1L8ZKLA), the problem disappears. If I have even one active binding (line 73 for instance), I get this annoying unfocus every 3-7 minutes.

**Comment by asmagill** [comment] 2016-09-27 17:10
I have seen similar behavior in Sierra, but was assuming it was due to some window watchers I have running and hadn't tracked it down yet... I don't seem to have the un-focus quite as often as you, more like every 20-30 minutes.

You say disabling the hotkey's fixes it, though?  I have noticed some other minor changes in the way Sierra handles the registered hotkeys (mostly that it's more sensitive to other modifiers like the `fn` key and there are a few more combinations that we can't override)... I have an idea on a replacement, but its going to take at least a week or so before I will have the time to get something ready for testing.

Are you able to test with Hammerspoon version `0.9.46` to help determine if the problem is specific to the newest release?  My suspicion is that it won't fix things, but if it does, that might make the fix easier to identify.

@cmsj, @lowne, other thoughts?

**Comment by unnamed777** [comment] 2016-09-28 03:34
> https://www.instagram.com/do4alab/
Yes, I didn't have the issue for two hours when I comment all of bindings.

I installed 0.9.46 just now, try to test it today.

**Comment by unnamed777** [comment] 2016-09-28 05:54
Behavior is the same on 0.9.46.

**Comment by unnamed777** [comment] 2016-10-26 10:03
Is there any news? This issue is killing me.

**Comment by lowne** [comment] 2016-10-26 12:20
I'm not on Sierra yet, so can't comment, but it does look like an OS bug (maybe in CoreGraphics).

**Comment by cmsj** [comment] 2017-09-05 16:21
I would suggest switching to Karabiner Elements for keyboard remapping, it can now do many of the complex things that Karabiner could do.

**Closed by cmsj** 2017-09-05 16:21 UTC
