### ISSUE TITLE
hs cli has /usr/local/ hard-coded? Breaks on Apple Silicon using /opt/homebrew

### ISSUE THREAD

**Issue by von** [Hammerspoon/hammerspoon#3088] opened 2022-01-23 15:23 UTC
It appears that the `hs` cli (as installed by [hs.ipc](http://www.hammerspoon.org/docs/hs.ipc.html)) has `/usr/local/` hard-coded to search for lua libraries. On newer macs with Apple silicon, Homebrew installs in `/opt/homebrew` and hence this breaks `hs` (see appended example). Is there a way to configure the paths which `hs` searches?

```
hs -c "hs.doc.builder.genJSON(\"/Users/von/homestuff/hammerspoon/MySpoons/Contexts.spoon\")" | grep -v "^--" > docs.json || rm -f docs.json
...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: module 'hs.doc.builder' not found:
        no field package.preload['hs.doc.builder']
        no file '/Users/von/.hammerspoon/hs/doc/builder.lua'
        no file '/Users/von/.hammerspoon/hs/doc/builder/init.lua'
        no file '/Users/von/.hammerspoon/Spoons/hs/doc/builder.spoon/init.lua'
        no file '/usr/local/share/lua/5.4/hs/doc/builder.lua'
        no file '/usr/local/share/lua/5.4/hs/doc/builder/init.lua'
        no file '/usr/local/lib/lua/5.4/hs/doc/builder.lua'
        no file '/usr/local/lib/lua/5.4/hs/doc/builder/init.lua'
        no file './hs/doc/builder.lua'
        no file './hs/doc/builder/init.lua'
        no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/hs/doc/builder.lua'
        no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/hs/doc/builder/init.lua'
        no file '/Users/von/.hammerspoon/lib/hs/doc/builder.lua'
        no file '/Users/von/.hammerspoon/MySpoons/hs/doc/builder.spoon/init.lua'
        no file '/Users/von/.hammerspoon/hs/doc/builder.so'
        no file '/usr/local/lib/lua/5.4/hs/doc/builder.so'
        no file '/usr/local/lib/lua/5.4/loadall.so'
        no file './hs/doc/builder.so'
        no file '/Applications/Hammerspoon.app/Contents/Frameworks/hs/doc/builder.dylib'
        no file '/Users/von/.hammerspoon/hs.so'
        no file '/usr/local/lib/lua/5.4/hs.so'
        no file '/usr/local/lib/lua/5.4/loadall.so'
        no file './hs.so'
        no file '/Applications/Hammerspoon.app/Contents/Frameworks/hs.dylib'
❯ which hs
hs is /opt/homebrew/bin/hs
❯ which lua
lua is /opt/homebrew/bin/lua
```

**Comment by cmsj** [comment] 2022-01-26 18:03
Thanks for reporting this, I need to dig into how we can fix this properly for both Intel and ARM macs.

**Comment by sisoe24** [comment] 2022-02-01 02:41
Same problem here: Hammerspoon 0.9.93, Intel macOS Catalina 10.15.7 

```bash
hs -c "hs.doc.builder.genJSON(\"$(pwd)\")" | grep -v "^--" > docs.json
...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: module 'hs.doc.builder' not found:
        no field package.preload['hs.doc.builder']
        no file '/Users/virgil/.hammerspoon/hs/doc/builder.lua'
        no file '/Users/virgil/.hammerspoon/hs/doc/builder/init.lua'
        no file '/Users/virgil/.hammerspoon/Spoons/hs/doc/builder.spoon/init.lua'
        no file '/usr/local/share/lua/5.4/hs/doc/builder.lua'
        no file '/usr/local/share/lua/5.4/hs/doc/builder/init.lua'
        no file '/usr/local/lib/lua/5.4/hs/doc/builder.lua'
        no file '/usr/local/lib/lua/5.4/hs/doc/builder/init.lua'
        no file './hs/doc/builder.lua'
        no file './hs/doc/builder/init.lua'
        no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/hs/doc/builder.lua'
        no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/hs/doc/builder/init.lua'
        no file '/Users/virgil/.hammerspoon/tools/hs/doc/builder.lua'
        no file ''
        no file '/Users/virgil/.hammerspoon/hs/doc/builder.so'
        no file '/usr/local/lib/lua/5.4/hs/doc/builder.so'
        no file '/usr/local/lib/lua/5.4/loadall.so'
        no file './hs/doc/builder.so'
        no file '/Applications/Hammerspoon.app/Contents/Frameworks/hs/doc/builder.dylib'
        no file '/Users/virgil/.hammerspoon/hs.so'
        no file '/usr/local/lib/lua/5.4/hs.so'
        no file '/usr/local/lib/lua/5.4/loadall.so'
        no file './hs.so'
        no file '/Applications/Hammerspoon.app/Contents/Frameworks/hs.dylib'
```

**Comment by cmsj** [comment] 2022-02-21 22:35
Actually I think this isn't specifically M1 related, I think this is a duplicate of #3054 which was fixed in 3198b3d986133b0a82053fb0870cfd3c1e67e0d8.

**Closed by cmsj** 2022-02-21 22:35 UTC

**Comment by nonissue** [comment] 2022-04-21 03:03
Just wanted to add my experience:

With an M1 MBP and macOS Monterey, I had to follow the steps in the API docs which state:

> You may need to pre-create `/usr/local/bin` and `/usr/local/share/man/man1` in a terminal using sudo, and adjust permissions so your login user can write to them.

I created the directories, and then used `sudo chown` to give my user write access to them. Do note that giving your login user write access to these directories may not be ideal from a permissions/security perspective.

**Comment by asmagill** [comment] 2022-04-21 04:30
It does default to `/usr/local`, but you can specify another directory prefix when invoking the installer: e.g. [hs.ipc.cliInstall("/opt/homebrew")](http://www.hammerspoon.org/docs/hs.ipc.html#cliInstall).

`/usr/local` is the default because at the time Homebrew was pretty much only using that directory prefix, and it's traditional in UNIX like systems for local customizations to go there.

@cmsj is it worth adding logic that decides the default based on architecture?

**Comment by cmsj** [comment] 2022-04-21 11:58
@asmagill I'm honestly not sure what we should do here - neither is more or less correct, we just went with /usr/local/ on x86 because it's there and writable and Homebrew used it. There's no real guarantee that /opt/bin/ will exist on ARM.
IIRC homebrew only moved their ARM stuff to /opt so they didn't have a migrated set of Intel things in /usr/local/ confusing later installed ARM things.
I suppose it's more reasonable to think about the sane default for the future, since the fleet of Intel macs will only ever shrink from where we are today, but I'm wary of trying to be too clever about it.

At the very least, I'd want to check what a completely blank install of macOS looks like on ARM these days - what the permissions and existence of /usr/local and /opt are.

**Comment by nonissue** [comment] 2022-04-21 12:42
@cmsj 

I should be able to do a clean install of Monterey on my m1 mbp tomorrow or Friday and have a look at ‘/usr/local’ and ‘/opt’ if that would be helpful?

**Comment by cmsj** [comment] 2022-04-21 12:51
It would, thanks. An `ls -la` of each directory would be very helpful

**Comment by von** [comment] 2022-07-22 13:08
It does appear the `hs` client correctly searches for the lua libaries in `/opt/homebrew` now with 0.9.97 (6267).
