### ISSUE TITLE
Regression in function hs.wifi.watcher in 0.9.52

### ISSUE THREAD

**Issue by lavir** [Hammerspoon/hammerspoon#1210] opened 2017-01-24 11:23 UTC
The Hammerspoon v.0.9.52 cannot init the hs.wifi.watcher

Message from MacOS (10.11.6) logs:
`24/01/17 08:27:55,460 Hammerspoon[1046]: (missing delegate):log level 2: hs.wifi.watcher:initManager unable to register for event type scanCacheUpdated: The operation couldn’t be completed. (com.apple.wifi.request.error error 4.)
`

It unable to register for all types of events, not only for 'scanCacheUpdated'

**Comment by cmsj** [comment] 2017-01-24 11:26
@asmagill at a glance, I'm wondering if this is a 10.11 vs 10.12 thing?

**Comment by asmagill** [comment] 2017-01-24 18:31
According to the docs, `CWEventTypeScanCacheUpdated` has been around since 10.10.  @lavir, is your configuration file available online or can you post the relevant section here?  I may have access to a 10.11 machine I can test on later this week.

**Comment by lavir** [comment] 2017-01-25 06:54
If you meant my lua script, then the relevant part is below:
```
local cbWifi = function ()
    net = hs.wifi.currentNetwork()
    print("wifi" ..net)

    if net==nil then
        hs.notify.show("wifi disconnected","","","")
    else
        hs.notify.show("wifi connected","",net,"")
    end
end

wifiwatcher = hs.wifi.watcher.new(cbWifi)
wifiwatcher:start()
```
Also I did fresh install of MacOS week ago, and then moved Hammerspoon.app and prefs from backup. Maybe this also affected on this issue. I'll clean up prefs and other files which are relates to Hammerspoon. 
I'll come back if I'll notice some changes.

**Comment by lavir** [comment] 2017-01-25 07:02
Ok, I did clean up. Didn't help.
BTW I have noticed a message in MacOS Logs
`25/01/17 08:55:46,953 airportd[62]: ERROR: Hammerspoon (29427) is not entitled for com.apple.wifi.events, will not register for event type 6
`
I have allowed access the Hammerspoon in Accessibility Prefs

**Comment by z3t0** [comment] 2017-01-25 07:08
Pretty sure this is a [bug](https://forums.developer.apple.com/thread/11307)

**Comment by asmagill** [comment] 2017-01-25 08:58
I can confirm that it does work in 10.12.3, so this may in fact be a limitation in 10.11.  I recently (i.e. within the last two releases I think) did a rewrite of the watcher code because we no longer formally supporting 10.9 and all of the API documentation said that the code I added was supported in 10.10+.  Sigh... I have identified a 10.11.6 machine I can test on but it will probably be later this week before I can fully explore this and work up a fix.  I should probably dust off an old laptop and install 10.10 as well, but that will take longer.

**Comment by lavir** [comment] 2017-01-25 09:54
I'll install Hammerspoon in wife's laptop, it should have 10.11. Let's see...

**Comment by lavir** [comment] 2017-01-25 10:01
Just in case checked previous versions of Hammerspoon.
So, 0.9.50 works well, 0.9.51 doesn't.

**Comment by cmsj** [comment] 2017-01-26 20:35
@asmagill if this is a bug in CoreWLAN, I'm not convinced that we should do a huge amount of hoop-jumping to work around it. Can just skip that event type in `HSWifiWatcherManager::init()` on 10.11?

**Comment by asmagill** [comment] 2017-01-27 05:56
I haven't had a chance to test this under 10.11 myself (this week went all wonky on me the last couple days)...  @lavir says that it is failing for all of the events, but I don't know yet if it is a case of since one is bad it marks the whole thing as invalid or if disabling the one will be sufficient.

I had two original reasons for the update:
 1. every time a wifi watcher was registered, any SSID change was causing *all* of the watcher callbacks to be invoked the same number of times as watchers defined (i.e. 1 watcher = 1 callback; 2 watchers = 4 callbacks -- 2 to each callback function; etc.)  and
2. there were more event types to be able to watch for (though honestly I only think a couple of them will be of any interest to anyone)...

Let me look at it this weekend.

**Comment by lavir** [comment] 2017-01-27 07:13
@asmagill once you fix this issue (at least I hope :) ) I can test the new (beta?) version.

**Comment by asmagill** [comment] 2017-01-30 08:49
@lavir, you can download the modified module at https://github.com/asmagill/hammerspoon_core/tree/master/wifi and test it if you like.  I want to test it some more myself before actually creating a pull-request and incorporating it into the core Hammerspoon application itself.

**Comment by lavir** [comment] 2017-01-30 12:50
Tested, works well! Did not notice any issue in logs.
Thank you!

**Comment by asmagill** [comment] 2017-04-03 18:57
since merged, am closing this.  reopen if you disagree.

**Closed by asmagill** 2017-04-03 18:57 UTC
Labels: bug, regression
