### ISSUE TITLE
Weird behaviour when config is a symlink

### ISSUE THREAD

**Issue by piranha** [Hammerspoon/hammerspoon#1101] opened 2016-11-28 09:32 UTC
I manage most of my config files by having a single repo with them, and linking them from the places they need to be in. 

But if I link Hammerspoon's config (instead of it being a real file), Hammerspoon starts to behave strangely: when I move mouse over it's menu icon, cursor changes to a rotating "waiting" one. And then if I click on it, menu takes 10 seconds to appear.

**Comment by cmsj** [comment] 2016-11-28 17:49
Huh, so this is really interesting. I run into the beachball cursor thing every now and then with Hammerspoon too, but I'd always just assumed it's because I'm running it from Xcode while working on it.

Do you have an easy way to reproduce the beachballing? And are you 100% sure it correlates with whether or not the config is a symlink? The weird thing here is that the init.lua file should hardly ever be read from disk - really only when the config is being reloaded.

**Comment by piranha** [comment] 2016-11-28 20:05
I have created the issue after trying this out twice and it made Hammerspoon to beachball. But now I can't reproduce it - no idea what to do next. I'll try to live with a symlink and report back if any problems arise.

**Comment by cmsj** [comment] 2016-11-28 20:06
ok thanks. I would like to get to the bottom of this, because it annoys me too :)

**Comment by cmsj** [comment] 2017-04-27 21:26
I'm going to close this out because there isn't enough detail to go on, but please re-open it if you disagree :)

**Closed by cmsj** 2017-04-27 21:26 UTC

**Comment by piranha** [comment] 2017-04-29 19:29
Yeah, it seems this was fixed since my report, since right now my config is a symlink and I have no problems. :)
