### ISSUE TITLE
hs image to nsimage crash

### ISSUE THREAD

**Issue by cmsj** [Hammerspoon/hammerspoon#732] opened 2016-01-16 21:56 UTC
http://crashes.to/s/a97a867cc3f looks like a null pointer dereference

**Comment by asmagill** [comment] 2016-01-16 23:56
I'm not in a position to test this until later tonight, but I *think* the problem is that luaL_testudata is returning NULL, as it's supposed to when the data isn't the correct userdata type, and then trying to assign it as a pointer to a pointer...

I think if you change this (in hs.image's internal.m):

~~~objc
static id HSImage_toNSImage(lua_State *L, int idx) {
    void **thingy = luaL_testudata(L, idx, USERDATA_TAG) ;
    if (*thingy) {
        return (__bridge NSImage *) *thingy ;
    } else {
        return nil ;
    }
}
~~~
 to
~~~objc
static id HSImage_toNSImage(lua_State *L, int idx) {
    if (luaL_testudata(L, idx, USERDATA_TAG)) {
        void **thingy = luaL_testudata(L, idx, USERDATA_TAG) ;
        if (*thingy) {
            return (__bridge NSImage *) *thingy ;
        }
    }
    return nil ;
}
~~~

(though to be honest, I don't like repeating luaL_testudata, so I'll try a few variants in the final fix)

It's because I'm trying to keep the helpers from erring with a lua error now, expecting the recipient to check for the nil/null... but in this case, it's not getting out of the helper function, so that's a problem.

Is this crash from something you're attempting to do or just a crash you happened to look at?  I ask because I'd like to know how to replicate it and see if this fix works later when I get a chance (if you don't get to it first).  If this fixes it, I think there are a few other places I'll probably need to check as well, so a good process to trigger it will help in troubleshooting.

**Comment by cmsj** [comment] 2016-01-18 20:42
@asmagill it was a crash that got reported by Crashlytics: http://crashes.to/s/a97a867cc3f (which means virtually no reproduction information, sadly)

**Comment by asmagill** [comment] 2016-01-19 12:34
i think the latest patch fixes this... i see we have a slate of new ones, though, this AM... i'll take a closer look this afternoon when i'm back from travelling

**Comment by asmagill** [comment] 2016-01-19 16:02
Actually it was the Crashlytics data that showed that the crash came through the lack of data type checking in the hs.pasteboard.setImageContents function... well, ok, I can't verify that it actually received bad data, but it gave me the idea and by sending a string to setImageContents, I could generate a crash in the same location.

**Closed by asmagill** 2016-01-19 16:02 UTC
