### ISSUE TITLE
Building from clone drops "Hammerspoon" dir in ~/

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#194] opened 2015-01-17 00:11 UTC
Just for fun I cloned the repo and built it using `xcodebuild -workspace Hammerspoon.xcworkspace -scheme Release`.

All went well, except that for some reason my $HOME was suddenly carrying a dir called "Hammerspoon" (note the lack of a dot), with apparently some kind of sample init file inside.

Is there a way to not have that dir appear?  Is my cmdline call incorrect?

Note that my clone of the repo is not under $HOME, though it's hard to see why that should matter.

**Comment by chdiza** [comment] 2015-01-17 00:31
It seems this same process also dumped a dir "extensions" into $HOME.

**Comment by cmsj** [comment] 2015-01-17 14:08
I'd be interested to see the text output of the build, but in general the best way to do a build is just to run "make"

**Comment by cmsj** [comment] 2015-01-17 14:09
(neither the "Hammerspoon" nor "extensions" directory should have appeared where they did, hence why I'd like to see the full output of the build!)

**Comment by chdiza** [comment] 2015-01-17 18:37
I just tried it again and couldn't reproduce.  I probably did something doofy :)

**Comment by chdiza** [comment] 2015-01-17 18:42
Incidentally, I tried "make".  I noticed that at the end it copies Hammerspoon.app from deep within ~/library/developer into `build`.  But this leaves two copies of Hammerspoon.app sitting on the machine.  Could the copy be a move instead?  Or is there a way to make Xcode not put Hammerspoon.app in ~/library/developer/blah in the first place?

**Comment by cmsj** [comment] 2015-01-17 22:14
@chdiza the location of build stuff seems to be a local user setting in Xcode, weirdly. I put the copy in so we could get the .app into a predictable location for anything else that needs it (e.g. My release script)

I make no claims of being an Xcode expert though!

**Comment by chdiza** [comment] 2015-01-19 02:46
I know nearly nothing about Xcode, but I know that despite my never having touched a setting in Xcode.app that affects the locations of builds, lots of different projects leave their .apps in lots of different places.

Hydra, Mjolnir, and Macvim leave it in build/release (or thereabouts); Slate leaves it in $project_dir/tmp.  Something else once leaves it in a location analogous to Hammerspoon, so it's not without precedent.

**Comment by cmsj** [comment] 2015-01-21 20:23
Since this wasn't reproducible, I'm going to close this out for now, but lemmie know if it rears its head again!

**Closed by cmsj** 2015-01-21 20:23 UTC

**Comment by chdiza** [comment] 2015-01-21 21:01
It happened again, twice, but when building Slate.  I think there might be an Xcode bug that occurs when calling `xcodebuild` from the command line.

**Comment by chdiza** [comment] 2015-01-21 21:42
It happened again, with Hammerspoon, but now I can see it is a Git problem, not Xcode.  I didn't attempt to build anything.  All I did was git pull my Hammerspoon repo.

UPDATE: This is all my fault because I suck at git.  I was using --git-dir with git-pull inside a shell script so that I could call `git pull` pull without cd-ing to my repo first.  Said script is executed from, you guessed it, ~/.

I'm going to try git -C my_clone_path --git-dir=my_clone_path/.git.
