### ISSUE TITLE
How to use fn as a mod key?

### ISSUE THREAD

**Issue by viogus** [Hammerspoon/hammerspoon#922] opened 2016-06-19 08:52 UTC
Or is there a module available to get this done?

I recently upgrade to macOS 10.12 , and found karabiner not working any more.
But my only  use of  Karabiner is to convert Fn key to hyper ("⌘", "⌥", "⌃", "⇧"),
And use hyper in my Hammerspoon config,
So is there a convenient way to map Fn to Hyper key or something like that?

Thank you all for bring us such a great tool.

**Comment by asmagill** [comment] 2016-06-21 23:34
`hs.eventtap` can detect the Fn modifier by watching for the `hs.eventtap.event.types.flagsChanged` event.

You can also check inside a hotkey callback to see if the Fn key is also being held down by looking at the results to `hs.eventtap.checkKeyboardModifiers()`... unfortunately you run into the issues described in #689.

**Comment by viogus** [comment] 2016-06-22 02:19
```lua
xyzzy = hs.hotkey.bind({}, "e",
  function()
    if hs.eventtap.checkKeyboardModifiers().fn then
      hs.alert.show("FN is DOWN!!!")
      -- toggle_application("Emacs")
    else
      xyzzy:disable()
      hs.eventtap.keyStroke({}, "e")
      xyzzy:enable()
    end
  end
)
```
@asmagill 
I have tried the code above , but it seems not working for 10.12.

**Comment by asmagill** [comment] 2016-06-22 03:17
Hmmm... while it worked for me back in December (don't recall what I was running then), it's not working for me now in 10.11.5, either...

Adding a little delay before re-enableing the hotkey seems to help:

~~~lua
xyzzy = hs.hotkey.bind({}, "e",
  function()
    if hs.eventtap.checkKeyboardModifiers().fn then
      hs.alert.show("FN is DOWN!!!")
      -- toggle_application("Emacs")
    else
      xyzzy:disable()
      hs.eventtap.keyStroke({}, "e")
      hs.timer.doAfter(0.1, function()
          xyzzy:enable()
      end)
    end
  end
)
~~~

**Comment by viogus** [comment] 2016-06-22 03:39
Noop,  it seems `hs.eventtap.checkKeyboardModifiers().fn` is dead on 10.12

after running the following snippet and pressing Fn key  gives nothing .

```lua
if hs.eventtap.checkKeyboardModifiers().fn then
  hs.alert.show("good fn key pressed")
end
```

**Comment by asmagill** [comment] 2016-06-22 04:01
It's an instantaneous check -- if you're not holding down `Fn` at the exact instant it does the check, it will return false...

Try the following in the Hammerspoon Console:
~~~lua
hs.hotkey.bind({"cmd","alt","shift","ctrl"},"e",function() print(hs.inspect(hs.eventtap.checkKeyboardModifiers())) end)
~~~

It hopefully will give you something similar to this:

~~~lua
> hs.hotkey.bind({"cmd","alt","shift","ctrl"},"e",function() print(hs.inspect(hs.eventtap.checkKeyboardModifiers())) end)

-- Loading extension: hotkey
hs.hotkey: keycode: 14, mods: 0x1b00 (0x7f86de514d48)
-- Loading extension: inspect
-- Loading extension: eventtap
{
  alt = true,
  cmd = true,
  ctrl = true,
  shift = true
}
{
  alt = true,
  cmd = true,
  ctrl = true,
  fn = true,
  shift = true
}
~~~

Then tap `Cmd-Option-Shift-Control E` both with and without the Fn key as well and let me know what it reports.

In truth, you may be right about `Fn` in 10.12... a little Googling shows that Apple has apparently made some significant changes at a pretty low-level regarding keyboards, so... we'll have to wait and see... but the output from this should at least give us an inkling

**Comment by asmagill** [comment] 2016-06-22 04:02
Ok, I pasted my output before the important line about trying the hotkey, but I think you get my meaning...

**Comment by viogus** [comment] 2016-06-22 04:19
`Fn-CMD-Option-Shift-Control ` +`E` gives no output.
while `CMD-Option-Shift-Control`+`E` gives
```lua
{
  alt = true,
  cmd = true,
  ctrl = true,
  shift = true
}
```
I guess it is broken for 10.12 dp1 now.

**Comment by asmagill** [comment] 2016-06-22 04:32
No output at all?  That's... interesting... it means that maybe CocoaEvents finally recognizes the Fn key as a unique modifier in 10.12, since the absence of output means it didn't trigger the callback at all... In the short run, I don't have a solution for you.  In the long run (fingers crossed), we *may* actually be able to support it more easily once I can get a hold of the SDK and look at the docs and (more importantly) header files.

**Comment by cmsj** [comment] 2016-06-22 11:41
@asmagill I don't see any indication that Fn is now supported in the Carbon/Events.h header in 10.12. NSEvent's key masks have been deprecated though, however, that shouldn't cause them to stop working, but I haven't had a chance to test it myself.
(We should try and figure out the answer soon though, if we're going to get Radars filed with Apple)

**Comment by asmagill** [comment] 2016-06-22 21:13
Those of you with 10.12beta, check out https://github.com/asmagill/hammerspoon_asm/tree/master/hotkey1012

It's a bit of a leap, but looking closely at `CocoaEvents.h` and `Events.h` and seeing how the `shiftKey`, `cmdKey`, and `optionKey` values are defined, I've added one for the Fn key following the same pattern...  As you'll see in the folder's `README.md` file, it doesn't work for 10.11 -- as expected, when registering the global hotkey, it's ignoring bit 17; but @viogus comments above show that when he holds down the `Fn` key, CocoaEvents is no longer matching that to the registered hotkey like 10.11 does... maybe that means we can now set it and have it honored.

At any rate, if you get a chance, let me know what the new code does... if it works, the module still needs to more updates... `hs.hotkey.getHotkeys()`, for example, doesn't know about the `fn` key yet and will mis-label things... however, I don't want to take the time to figure it out unless this works...

**Comment by cmsj** [comment] 2016-06-22 21:31
@asmagill sorry to say that it doesn't work in 10.12

**Comment by asmagill** [comment] 2016-06-22 21:39
Same error as I get in 10.11?

**Comment by asmagill** [comment] 2016-06-22 21:39
oh, just saw the last half of your comment...

**Comment by asmagill** [comment] 2016-06-22 21:58
I may have to resurrect the attempt to migrate hotkey to a fully eventtap based model... I'll have to figure out how to get around the key-drops I sometimes experienced, though... at any rate, unless inspiration hits, I'm out of ideas until I can get 10.12 myself and try some things out.

@cmsj as to your idea about submitting an rdar... your call -- as I understand it, RegisterEventHotKey is (still) not allowing the setting of the `fn` key modifier, but the Cocoa event handler is now (in 10.12) distinguishing between key events with and without the `fn` modifier...

**Comment by cmsj** [comment] 2016-08-24 19:05
Hmm, damn, I forgot about this issue and just recently moved my laptop back to 10.11. I can't live without Karabiner, so it was very annoying to run 10.12!
I guess I can try again when we get closer to release and see if I can reproduce and/or fix this, if someone else hasn't gotten there first.

**Comment by asmagill** [comment] 2016-08-24 19:23
I've currently got 10.12 on an another laptop that I access occasionally via Screen Sharing... I've noticed that when the machine has been idle with Hammerspoon running for a day or so, it gets extremely slow... so slow that I've had to ssh into the machine and kill Hammerspoon just to get to the lock-screen to show up in Screen Sharing... while I'm doing quite a bit that's "bleeding edge" with Hammerspoon, the same configuration (they're about 99% identical) works fine under 10.11 with no slowdowns ever...

Upshot, we definitely need to formally test and regularly use Hammerspoon in 10.12 because there are going to be differences/issues... another reason I'm eager for a formal release so I can get back to being closer to core and a known "stable" state before making more changes.

I'm planning to swap machines this weekend (use the 10.12 machine daily and access the 10.11 remotely), so that will help identify what areas of concern we may have... To my knowledge, we have this issue and maybe something (possibly inconsistent) with hs.caffeinate re #924?  And my spaces module needs to be stress tested under 10.12, since that seems to be a popular 3rd party addition.

**Comment by cmsj** [comment] 2016-08-24 19:31
@asmagill ok, if we can have everything for 0.9.47 in by Friday, I should be able to do a release over the weekend.

**Comment by quickdraw6906** [comment] 2017-02-18 07:36
Here is how I trap holding the function key. Works in Sierra. This way is important because if the only other keys being held at the time are modifiers, the normal keyDown event does not fire.

-- Map PC keyboard keys to pasteboard functions
-- Have to trap flagsChanged event instead of keyDown because 
-- holding only modifier keys doesn't trigger a keyDown event
hs.eventtap.new({hs.eventtap.event.types.flagsChanged}, function (e) -- 12 = nkeyDown	
	-- If Function key held
	if e:getFlags().fn then
		-- If control key held
		if hs.eventtap.checkKeyboardModifiers().ctrl then
			-- Doing both because some apps roll there own key/menu interpretation
			-- Which ever is not used by an app will cause a beep [sad face]
			hs.eventtap.event.newKeyEvent({"cmd"}, "C", true):post()
			hs.eventtap.event.newKeyEvent({"cmd"}, "C", false):post()
			hs.eventtap.event.newKeyEvent({"ctrl"}, "C", true):post()
			hs.eventtap.event.newKeyEvent({"ctrl"}, "C", false):post()			
		end
		-- If shift key held
		if hs.eventtap.checkKeyboardModifiers().shift then
			hs.eventtap.event.newKeyEvent({"cmd"}, "V", true):post()
			hs.eventtap.event.newKeyEvent({"cmd"}, "V", false):post()
			-- Can't do both because some apps (TextMate) have functions for CTRL+V
			--hs.eventtap.event.newKeyEvent({"ctrl"}, "V", true):post()
			--hs.eventtap.event.newKeyEvent({"ctrl"}, "V", false):post()
		end		
	end	
end):start()

**Comment by cmsj** [comment] 2017-04-27 21:06
I'm not sure there's much more we can do on this, so I'm going to close it out. If anyone disagrees, please re-open :)

**Closed by cmsj** 2017-04-27 21:06 UTC
