### ISSUE TITLE
High resolution to Low resolution layout change - should it consider the dock/resolution?

### ISSUE THREAD

**Issue by deepumukundan** [Hammerspoon/hammerspoon#226] opened 2015-02-19 21:05 UTC
I have these 2 display configs. (Stripping down to show the problematic area)

local internal_display = {
    {"Google Chrome",     nil,          display_laptop(), hs.layout.maximized, nil, nil},
    {"Xcode",             nil,          display_laptop(), hs.layout.maximized, nil, nil},
}
Size - 1440 x 900, Extreme left display of 3, Dock on the right side

local triple_display = {
    {"Google Chrome",     nil,          display_middle(),  hs.layout.maximized, nil, nil},
    {"Xcode",             nil,          display_middle(),  hs.layout.maximized, nil, nil},
}
Size - 1920 x 1080, Middle Display of 3, No Dock

When the external monitors are unplugged, a screen watcher will switch to internal display config.
Now when that happens, the windows go outside the screen bounds behind the dock. I could iterate on the windows and ask hs.window.ensureIsInScreenBounds / hs.window.maximize. But would that be the right way or should the layout manager subtract the dock and resize it based on the screen resolution?

**Comment by cmsj** [comment] 2015-02-20 14:12
Yeah this is a weird one, when a window is maximised and moves to a smaller screen, you have to resize it shorter than the full height, otherwise it doesn't resize. You'd likely find that even ensureIsInScreenBounds() wouldn't work, because that would also be trying to resize it to the maximised size.

I think there is some lower level system stuff going on which makes windows behave slightly stickily when they're maximised. From my testing, you'd have to make the window about 30 pixels shorter than maximised, and then maximise it. We could have hs.layout do this, but it would make the operations take longer and look weird as the window jumped around a bit.

**Comment by deepumukundan** [comment] 2015-02-20 20:28
Got it. It is not a big pain. I could resize them via keyboard shortcuts.

**Comment by cmsj** [comment] 2015-02-21 19:59
FWIW, I think what we're seeing here (the stickiness around the dock) has been reported already, so I'm going to close this as a duplicate of #217

**Closed by cmsj** 2015-02-21 19:59 UTC

**Comment by deepumukundan** [comment] 2015-02-21 20:52
Np. Thanks for looking into this!
