### ISSUE TITLE
How to convert mouse button to keystroke?

### ISSUE THREAD

**Issue by LunaticoCR** [Hammerspoon/hammerspoon#1519] opened 2017-08-25 12:05 UTC
Hi,

I'm trying to write a script that would allow me to turn my middle mouse button into a left alt key. I'm going through the documentation but can't quite figure it out. I'm quite new to lua which probably doesn't help.

I would have thought something like this would do the trick:
```
-- Map the middle mouse to the alt key
eventtapMiddleMouseDown = hs.eventtap.new({ hs.eventtap.event.types.middleMouseDown }, function(event)
	hs.alert.show("middleMouseDown")
	hs.eventtap.event.newKeyEvent("alt", "", true):post()
	return false
end)
eventtapMiddleMouseDown:start()
```

I think I have two problems, the first is that ```hs.eventtap.event.types.middleMouseDown``` doesn't seem to work, if I change it with ```hs.eventtap.event.types.rightMouseDown``` that does work. The other problem is the way I'm trying to generate the alt key, I don't think that's working either.

Any help with this would be highly appreciated!

Thanks.

**Comment by asmagill** [comment] 2017-08-28 21:40
First, I don't know why your middle mouse button isn't triggering the callback... does your mouse support software maybe remap the middle mouse to some other function (I think I remember seeing this with an older logitech mouse -- I had to tell the software explicitly to send a third mouse click, it didn't by default)

Second, this isn't quite right and third, I don't believe that the current eventtap module can do what I think you want (more on that in a bit)

I think what you really want is something more like this:

~~~lua
eventtapMiddleMouseDown = hs.eventtap.new({ hs.eventtap.event.types.middleMouseDown, hs.eventtap.event.types.middleMouseUp }, function(event)
    if (event:getType() == hs.eventtap.event.types.middleMouseDown then
        return true, { hs.eventtap.event.newKeyEvent(hs.keycodes.map.alt, true) }
    else
        return true, { hs.eventtap.event.newKeyEvent(hs.keycodes.map.alt, false) }
    end
    return false -- shouldn't ever reach here, but just in case
end):start()
~~~

Now as to why I don't think it will work the way you expect... it's because Hammerspoon posts its events into a private queue, so this *will* affect other key event posts generated from within Hammerspoon, but not the global environment.  When eventtap is modified so that it posts directly into the combined queue, it breaks a number of expected behaviors.  I do have plans for an update to eventtap at some point, and may add the ability to choose which queue to inject the event into, but at present there is no eta for the updated module -- it's a fundamental rewrite to address slow downs and dropped events under load and keeping it backwards compatible and/or not breaking other things is proving to be a big PITA.

**Comment by LunaticoCR** [comment] 2017-08-29 10:59
Thanks very much for your reply @asmagill.
I tried the bit of code you posted but that's not working either, it doesn't even seem to go into the if statements. If I change middleMouseDown with rightMouseDown in the script then that does work, although it didn't seem to trigger the alt key press.

> does your mouse support software maybe remap the middle mouse to some other function

I guess you mean is my mouse backed by its own software? In that case the answer is no, I have a *Microsoft Sculpt Ergonomic Mouse* and it's just plug and play.

To give you some background of why I'm doing this. I used Karabiner to achieve this, remapping the middle mouse button to the left alt key. And then through BetterTouchTools I have it so that the mouse can drag the window it's over while the alt key is being pressed. This obviously broke with Sierra and the new Karabiner-Elements can't remap mouse keys.

The Karabiner-Elements event viewer does seem to suggest that my middle mouse is triggering the right events.
![screenshot at aug 29 11-46-39](https://user-images.githubusercontent.com/2124383/29817843-86a5b858-8cb1-11e7-8c9a-6693f156bdc0.png)

**Comment by LunaticoCR** [comment] 2017-08-29 14:11
I've switched to use otherMouseDown and now I'm capturing the middle mouse fine. The event:eventType() gives me 25 for down and 26 for up. There was also a parameter (empty list) missing for newKeyEvent. The middle mouse click is now generating alt down and up, but it's only a very quick single keypress.

This is how it looks now:
```
-- Map the middle mouse to the alt key
eventtapOtherMouseDown = hs.eventtap.new({ hs.eventtap.event.types.otherMouseDown, hs.eventtap.event.types.otherMouseUp }, function(event)
    if (event:getType() == hs.eventtap.event.types.otherMouseDown) then
    	hs.alert.show("otherMouseDown" .. event:getType())
        return true, { hs.eventtap.event.newKeyEvent({ }, hs.keycodes.map.alt, true) }
    else
    	hs.alert.show("otherMouseUp" .. event:getType())
        return true, { hs.eventtap.event.newKeyEvent({ }, hs.keycodes.map.alt, false) }
    end
    return false -- shouldn't ever reach here, but just in case
end):start()
```

It seems like I'm very close to achieving what I want, the only thing I'm missing is the ability to keep the alt down while I have the middle button pressed down, and only release the alt when I release the middle button. I would have thought the code as it is should do it, down on the if and up on the else, but that doesn't seem to be the case.

Do you know if this would be possible?

**Comment by asmagill** [comment] 2017-08-29 16:05
Ah yes, the middle vs other issue is better addressed in the master branch but not the latest release.  otherMouse is more "correct" (i.e. it follows Apple's naming conventions) and middleMose is supposed to be identical for backwards compatibility, but there was a mistake in the last release that broke it in some places.

I don't know why you need the empty table for newKeyEvent; it's supposed to detect when that is missing and treat it as nil.

As to the momentary nature of the press, I'm not sure... try the following and see if it's any better (and if it is, then we've got another bug...)

~~~lua
-- Map the middle mouse to the alt key
eventtapOtherMouseDown = hs.eventtap.new({ hs.eventtap.event.types.otherMouseDown, hs.eventtap.event.types.otherMouseUp }, function(event)
    if (event:getType() == hs.eventtap.event.types.otherMouseDown) then
    	hs.alert.show("otherMouseDown" .. event:getType())
    	hs.eventtap.event.newKeyEvent({ }, hs.keycodes.map.alt, true):post()
        return true
    else
    	hs.alert.show("otherMouseUp" .. event:getType())
        hs.eventtap.event.newKeyEvent({ }, hs.keycodes.map.alt, false):post()
        return true
    end
    return false -- shouldn't ever reach here, but just in case
end):start()
~~~

I've moved the events out of the "pass through replacement" and back to independent posting.  I'll try and take a look tonight at why the empty table is required and if that is also a release vs master issue or if it needs to be addressed directly before the next release as well.

And it's BTT that's doing the actual window movements?  I'll see if I can install that tonight and test this directly myself as well.

**Comment by LunaticoCR** [comment] 2017-08-30 07:44
Ok, so that new version you posted does work, but so does one with the "pass through replacement". After my last post I did some further modifications and got it working better. On this last version I just separated the down and up into different blocks, I also send a modifier 'alt' on the mouse down. I did this because when I look at the events on the Karabiner-Elements EventViewer for the keyboard alt keypress it looks like this:
![image](https://user-images.githubusercontent.com/2124383/29832230-6def1b32-8cdf-11e7-8523-01c27cd23ad0.png)

So now when I press the middle mouse, it seem to be generating the exact same events as when I press the alt key, and when I keep it pressed, it is staying pressed. I'm testing this on the System Preferences -> Keyboard -> Input Sources, when you press alt the keyboard layout is changed, if you keep it pressed it stays changed.

This is how my code looks now, not sure if this is more or less efficient than having it on a single block:
```
-- Map the middle mouse to the alt key
eventtapOtherMouseDown = hs.eventtap.new({ hs.eventtap.event.types.otherMouseDown }, function(event)
    if (event:getType() == hs.eventtap.event.types.otherMouseDown) then
    	hs.alert.show("otherMouseDown" .. event:getType())
        return true, { hs.eventtap.event.newKeyEvent({ 'alt' }, hs.keycodes.map.alt, true) }
    end
    return false -- shouldn't ever reach here, but just in case
end):start()

eventtapOtherMouseUp = hs.eventtap.new({ hs.eventtap.event.types.otherMouseUp }, function(event)
    if (event:getType() == hs.eventtap.event.types.otherMouseUp) then
    	hs.alert.show("otherMouseUp" .. event:getType())
        return true, { hs.eventtap.event.newKeyEvent({ }, hs.keycodes.map.alt, false) }
    end
    return false -- shouldn't ever reach here, but just in case
end):start()
```

Now, this brings me to sad news, even as it is, where I'm at a point where the middle mouse button seems to be properly remapped to the alt key, BTT is not doing the window move as expected.

And to answer your question, yes BTT has this functionality:
![image](https://user-images.githubusercontent.com/2124383/29832395-fecaf4d2-8cdf-11e7-9d7b-c2556a99e815.png)

**Comment by asmagill** [comment] 2017-09-01 02:37
Tried out with BTT and I see the same behavior as you do, so I'm going to say that the current implementation of `hs.eventtap` can't do what you want.

However, check out https://github.com/asmagill/hammerspoon-config/blob/master/_scratch/otherMouseWindowMove.lua for an entirely Hammerspoon alternative that meets what I think you're trying to accomplish.

**Comment by LunaticoCR** [comment] 2017-09-04 10:33
Thanks @asmagill, I tried that script and it works, however, it is very laggy. It's more like a window chase mouse than a mouse move window.
Ideally what I was looking for was to move a window with a single press, in other words to move window while middle mouse pressed. As opposed to click to grab and click to release window.
I can achieve the same behaviour as this script with BTT, but not as laggy.
Looks like I'll have to be patient for Karabiner-Elements to bring back mouse remapping functionality.

**Comment by cmsj** [comment] 2017-09-04 19:29
I think it's safe to say that we're pretty unlikely to try and tackle the work done by BTT and/or Karabiner Elements, so if those can provide the solution, it would be best to stick with them.

(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)

**Closed by cmsj** 2017-09-04 19:29 UTC
Labels: needs-response

**Comment by LunaticoCR** [comment] 2017-09-05 08:41
I agree @cmsj ! Thanks guys for all your help.
