### ISSUE TITLE
Mouse click event in 6 button mouse

### ISSUE THREAD

**Issue by Ashish-Bansal** [Hammerspoon/hammerspoon#1468] opened 2017-06-21 17:11 UTC
Hi,

I'm trying to setup callbacks for mouse button clicks other than left and right buttons.
According to the API[0], there are events :

```
otherMouseDown -- Specifies a mouse down event with one of buttons 2-31.
otherMouseUp -- Specifies a mouse up event with one of buttons 2-31.
```

which correspond to button clicks other than left and right. Am I right ? 

If yes, when I register for these events, my callback function doesn't called on those button clicks.
```
leftMouseDown -- Specifies a mouse down event with the left button.
leftMouseUp -- Specifies a mouse up event with the left button.
rightMouseDown -- Specifies a mouse down event with the right button.
rightMouseUp -- Specifies a mouse up event with the right button.
```
I tried using it for left and right mouse events^, it works fine. 

Any suggestions ? 

I'm trying it on Logitech G102 gaming mouse.

[0] http://www.hammerspoon.org/docs/hs.eventtap.event.html

Thanks!

**Comment by cmsj** [comment] 2017-06-29 09:37
This seems to be an API bug on our part, use `hs.eventtap.event.types.middleMouseDown` (and `middleMouseUp`) to receive all of the "other" mice buttons than left and right, then when the event is passed to your callback, `event:getProperty(hs.eventtap.event.properties.mouseEventButtonNumber)` will tell you which other button was pressed.

@asmagill This seems to be down to `pushtypestable()` in `event.m` - it puts `middleMouse{Down,Up}` in the table, but the docs say `otherMouse{Down,Up}`. I'm thinking that the `other` version is more useful, since it covers buttons other than the middle mouse button, so I'm thinking we switch the table pusher to insert that. It'll break anyone who's using `middleMouse` variants, but since the docs don't mention that, it shouldn't matter. Any dissent? :)

**Comment by cmsj** [comment] 2017-06-30 08:15
Closing as a dupe of #1385

**Closed by cmsj** 2017-06-30 08:15 UTC
Labels: bug

**Comment by Ashish-Bansal** [comment] 2017-06-30 08:27
@cmsj Thanks a lot!
