### ISSUE TITLE
Suggestions for debugging an infrequently hanging Hammerspoon?

### ISSUE THREAD

**Issue by von** [Hammerspoon/hammerspoon#2923] opened 2021-07-26 18:17 UTC
Once or week or so Hammerspoon seems to hang - it's unresponsive, I get a beachball when I hover over the menu bar icon, and if I open the Force Quit menu, it shows as unresponsive. My fix currently is to Force Quit and restart it.

Console output isn't showing anything irregular when its hung and I haven't been able to discern correlation with anything as a possible cause (it may be hung for a while before I notice). No doubt it could be something in my configuration, probably a race condition, but given it's not readily reproducible, turning off parts of my configuration to try and debug would seem to be a royal pain.

Anyone have any guidance for how to go about debugging this?

TIA.

**Comment by latenitefilms** [comment] 2021-07-26 20:39
Can you share your config and/or the crash report when you force quit it? What version of Hammerspoon and macOS?

**Comment by von** [comment] 2021-07-29 00:40
Thanks for the response. I have my config in a private repo and it's rather large (>4000 lines total). if you are really serious about wanting to look through it, I can do a quick redaction of private content and post it. I do have [some of my Spoons in Github](https://github.com/von?tab=repositories).

I didn't know Force Quit created a Crash Report. I don't see any Crash Reports now when I look in the Console app but I just upgraded to 11.5 so I'm guessing they got overwritten. l'll look for one next time I run into the problem.

In terms of versions: Max OS X 11.5 and Hammerspoon 0.9.90 (6030).

Thanks again.

**Comment by asmagill** [comment] 2021-07-29 01:05
It might also be instructive to see how much memory Hammerspoon is claiming when it's seeming hung... If it's particularly larger then usual, then it means we've got a memory leak somewhere (it wouldn't be the first time, and I know of at least one in the current release's `hs.canvas` module that I've posted a fix for, #2901, but it needs a little more testing before it's safe to land).

Open up the Activity Monitor and look at the memory usage for Hammerspoon... it's probably useful to check it every so often so you can get a feel for what your configuration *usually* looks like, then you have something to compare it to when it hangs.

**Comment by nielsbom** [comment] 2021-11-21 12:39
I have the same, only Force Quit fixes the problem. I think I've had this problem since updating to macOS 12 Monterey.

Adding info for debugging purposes:
* [config](https://gist.github.com/nielsbom/2904f6daf171ea258a617ca954fa2571)
* MacOS 12.01 (Monterey)
* Hammerspoon 0.9.90
* memory usage: 27 MB (seems reasonable)
* CPU usage: 0%

My console gives "spindump": `Hammerspoon [77828]: hang likely: not sampling due to conditions 0x400000000`. I have no idea what that means.

**Comment by nielsbom** [comment] 2021-11-24 13:36
FYI: I've got a non-responsive Hammerspoon every couple of hours now.

**Comment by hopefulwerewolf** [comment] 2021-11-29 21:02
I've been looking into this problem as well and ultimately traced it down to hs.window.filter.defaultCurrentSpace:getWindows() calls which I was using in multiple places (often as part of an hs.chooser callback to make sure I was taking the corresponding action in the correct window). At some point this started happening (maybe macOS Monterey?) but it didn't occur to me as the cause for a while.

Don't have a workaround (other than not using it).

https://github.com/Hammerspoon/hammerspoon/issues/2943

**Comment by von** [comment] 2021-11-29 22:22
FYI, I don't explicitly use `hs.window.filter.defaultCurrentSpace:getWindows()` but do use the `getWindows()` method on `hs.window.filter` objects in various callbacks in such a way it could be the problem.

**Comment by jdtsmith** [comment] 2021-11-29 22:26
I use `allWindowsForSpace` quite often.  I've noticed that HS hangs often when there is a frozen app in the background.  Killing that alleviates the freezes (often).  Maybe getWindows + frozen or non-responsive app is the culprit?

**Comment by hopefulwerewolf** [comment] 2021-11-30 03:42
I tried to troubleshoot a little deeper on my end and the issue was happening specifically on accessing `hs.window.filter.defaultCurrentSpace` and not the `getWindows()` method.

It was oddly enough not happening with hs.window.filter.default (or was happening for a barely noticeable time rather than for multiple seconds).

I tried to dig a bit deeper but didn't really get super far.

I think this section is relevant: https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/window/window.lua#L84-L89

**Comment by jubr** [comment] 2021-12-07 15:45
I'm sometimes also noticing the unresponsive delay. From the code refs and comments on this page it follows that Hammerspoon will become unresponsive if one of the applications it queries with `app:allWindows()` is unresponsive. My usual suspects seem to be IntelliJ + WebStorm.

@asmagill What could be a way to circumvent this? Is there existing macOS functionality to query app responsiveness before attempting a risky `app:allWindows()`? Or perhaps doing this block-worthy work on a separate thread and return the results to HS asynchronously, so the rest of processing does not block?

**Comment by jubr** [comment] 2021-12-07 15:55
LOL, it's already available `hs.application.isUnresponsive()` @ https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/application/libapplication.m#L252-L258

**Comment by n8henrie** [comment] 2022-01-27 21:23
I'm seeing a similar issue since moving to an M1 Mac about a year ago -- every few weeks I notice a trigger suddenly doesn't work, and when I look in Activity Monitor I see hammerspoon, highlighted in red "not responding". After I kill and restart everything is fine again. I've tried to "Sample Process" but don't understand the output.

I'll check Console.app next time and post here. 

HS 0.9.93, MacOS 12.1

**Comment by n8henrie** [comment] 2022-02-04 23:30
<img width="1432" alt="Screen Shot 2022-02-04 at 16 30 10" src="https://user-images.githubusercontent.com/1234956/152616671-ccce047c-7a3a-400d-8cd1-326ad8d8a5ab.png">

No messages in console:

<img width="781" alt="Screen Shot 2022-02-04 at 16 30 43" src="https://user-images.githubusercontent.com/1234956/152616716-2f2354f3-7a4a-4ac7-bf53-81947de88e9a.png">

¯\\\_(ツ)_/¯

**Comment by n8henrie** [comment] 2022-02-04 23:35
Perhaps some kind of deadlock in JXA evaluation?

<img width="1342" alt="Screen Shot 2022-02-04 at 16 34 41" src="https://user-images.githubusercontent.com/1234956/152616987-2ccfc5a6-91f1-4cb0-8a33-74c99761669b.png">

**Comment by n8henrie** [comment] 2022-02-05 01:25
After the above suggested it was a problem in the JXA evaluation, I think I figured it out.

I had launched MacVim with my hammerspoon keyboard shortcut:

```lua
hs.hotkey.bind(
  hyper,
  "V",
  nil,
  run_javascript("~/gists/f3abd106f6da2928b0b6a767a12f4b78/Open in MacVim.js")
)
```

where you can see that script here: <https://gist.github.com/n8henrie/f3abd106f6da2928b0b6a767a12f4b78>

I can't remember *why* I decided to use lua to call JXA to call a shell script...

but regardless, Hammerspoon was apparently stuck waiting for that to all close out. As soon as I quit MacVim, all of the pending hammerspoon triggers that I'd called in the meantime all fired at once and it was responsive again.

So I don't know if that helps anyone else debug, but `Activity Monitor` -> hammerspoon (double click) -> sample -> display `percent of thread` was helpful for debugging in this case.

**Comment by pbdeuchler** [comment] 2022-11-01 16:56
Major kudos to @n8henrie for debugging this, I'm experiencing the exact same issue when trying to open a specific webpage in Chrome (i'm assuming due to the way Chrome manages threads/processes/sandboxes):

```
    2568 Thread_240117   DispatchQueue_20: com.apple.root.user-interactive-qos.overcommit  (concurrent)
    + 2568 start_wqthread  (in libsystem_pthread.dylib) + 8  [0x19c04ce20]
    +   2568 _pthread_wqthread  (in libsystem_pthread.dylib) + 228  [0x19c04e0c4]
    +     2568 _dispatch_worker_thread2  (in libdispatch.dylib) + 164  [0x19bedd7c0]
    +       2568 _dispatch_root_queue_drain  (in libdispatch.dylib) + 684  [0x19bedd0b4]
    +         2568 _dispatch_client_callout  (in libdispatch.dylib) + 20  [0x19becb504]
    +           2568 _dispatch_call_block_and_release  (in libdispatch.dylib) + 32  [0x19bec99dc]
    +             2568 __45-[NSConcreteTask launchWithDictionary:error:]_block_invoke_2  (in Foundation) + 40  [0x19d0a5450]
    +               2568 __create_task_block_invoke  (in libtask.dylib) + 116  [0x112248234]
    +                 2568 _dispatch_sync_f_slow  (in libdispatch.dylib) + 144  [0x19beda934]
    +                   2568 __DISPATCH_WAIT_FOR_QUEUE__  (in libdispatch.dylib) + 368  [0x19bedad88]
    +                     2568 _dispatch_thread_event_wait_slow  (in libdispatch.dylib) + 56  [0x19becbca8]
    +                       2568 _dlock_wait  (in libdispatch.dylib) + 56  [0x19becbef4]
    +                         2568 __ulock_wait  (in libsystem_kernel.dylib) + 8  [0x19c014ba4]
```

**Comment by pbdeuchler** [comment] 2022-11-01 16:58
I can consistently reproduce this with just this lua snippet (copied from somewhere on SO):
```
function ChromeWithProfile()
  local profile = "Default"
  local url = "https://meet.google.com"
  local t = hs.task.new("/Applications/Google Chrome.app/contents/MacOS/Google Chrome", 
  nil,
  function() return false end,
  { "--profile-directory=" ..profile, url})
  t:start()
end
hotkey.bind(mash, 'D', ChromeWithProfile)
```

**Comment by homerjam** [comment] 2023-03-16 16:17
Has anyone found a temporary solution to this? I'm also getting inconsistent hangs on Ventura (pretty sure the same task was working prior to upgrading yesterday)

**Comment by homerjam** [comment] 2023-03-16 16:31
FWIW I'm using `hs.task` to run sh scripts (run node server, open browser windows), and then `hs.window` and `hs.screen` to position said windows. There's also `hs.timer` to deal with async/scheduling of tasks.

I was working locally on Monteray and testing remotely on Ventura previously - I had issues on Ventura which I put down to something else. However since I upgraded to Ventura locally I have the issues on both machines.

**Comment by cmsj** [comment] 2023-03-16 16:37
@pbdeuchler I think that was a usage of `hs.execute()` or `os.execute()` which are also blocking.

For launching browsers, I would recommend a pattern like this (which is a function I use with the URLDispatcher spoon):

```lua
function open_work_url(url)
    local browserPath = "/Applications/Microsoft\\ Edge/Contents/MacOS/Microsoft\\ Edge"
    local browserName = "Microsoft Edge"
    local browserProfile = "Work"
    local browserArgs = "--args --profile-directory='"..browserProfile.."'"

    pos, _ = string.find(url, "https://meet.google.com/", 1)
    if pos == 1 then
        browserArgs = browserArgs.." --new-window"
    end

    local execute = "/usr/bin/open -na '"..browserName.."' --args "..browserArgs.." '".. url .."'"

    hs.execute(execute)
end
```

using `/usr/bin/open` means the OS itself takes responsibilty for doing the launching and it returns very quickly.

**Comment by cmsj** [comment] 2023-03-16 16:40
@homerjam is there a specific bit of your config that is causing Hammerspoon to stop responding? I don't think that is correct (permission being required for background tasks).

**Comment by homerjam** [comment] 2023-03-16 16:42
> @homerjam is there a specific bit of your config that is causing Hammerspoon to stop responding? I don't think that is correct (permission being required for background tasks).

Not as far as I can tell, I have tried endless combinations and running each task in isolation and there is nothing that remains consistent

**Comment by PhrantiK** [comment] 2023-05-25 09:19
> I can't remember _why_ I decided to use lua to call JXA to call a shell script...
> 
> EDIT: I think it's because I want the trigger to act on an existing selection in Finder, and I haven't figured out how else people are doing that

I randomly figured this out recently. 

I have a shell script wrapped in a .app that uses applescript to get the selection but it's a bit janky, going to see if using hammerspoon works a bit better. 

I've got as far as listing the paths in the console:

````
local ax = require("hs.axuielement")

local function printSelectedFileURLs()
  local selectedChildren = ax.applicationElement("Finder").AXFocusedUIElement.AXSelectedChildren

  for _, child in ipairs(selectedChildren) do
    for _, sub in ipairs(child) do
      local url = sub:attributeValue("AXURL")
      if url and url.filePath then
        print(url.filePath)
      end
    end
  end
end

hs.hotkey.bind(hyper, 'm', printSelectedFileURLs)
````

It seems responsive even with quite a few files selected. Not sure if it's possible to remove that inner loop or not, tried but I can't figure it out.

**Comment by vojtechkral** [comment] 2024-04-19 12:30
Hi. I just ran into a similar issue launching processes, and I have a theory: I think at least some of the issues here happen due to garbage collection.

On my machine, this is enough to reproduce the hang:

```lua
hs.hotkey.bind('ctrl-cmd', 'return', function() io.popen("alacritty") end)
```

Some observations: The command doesn't produce output and it doesn't seem to matter whether or not output is redirected. The hang also doesn't happen right away, it always takes a couple of seconds for Hammerspoon to hang up.

I _think_ what happens is that the object returned by `io.popen()` gets garbage-collected at some point and the runtime ends up waiting for the process to finish. Indeed, when I instead persist the object in a global variable, the hang doesn't happen:

```lua
pipes = {}
hs.hotkey.bind('ctrl-cmd', 'return', function()
    pipes[#pipes+1] = io.popen("alacritty")
end)
```

Interestingly, with this code the hang happens _when I press reload config_, which I think confirms the GC hypothesis, because that's when the `pipes` variable goes out of scope.

I'm not entirely sure why the runtime waits for forked processes as well, perhaps it's awaiting the entire child process group.

To work around the problem I'm currently using this invocation:

```lua
hs.hotkey.bind('ctrl-cmd', 'return', function() hs.execute("alacritty & disown") end)
```

this removes the process from the child group and reparents it to the init process.

**Comment by von** [comment] 2024-05-19 20:59
@vojtechkral I don't have alacritty installed nor am I familiar with it. Can you offer an alternative command that recreates the problem? Or what are the key attributes of alacritty that cause the issue?

**Comment by Bellavene** [comment] 2024-06-04 20:44
&> /dev/null & disown
After every command is the answer

**Closed** 2024-09-12 18:21 UTC
