### ISSUE TITLE
is hs.eventtap.event.newSystemKeyEvent broken/changed in 0.9.56 for arrow keys ?

### ISSUE THREAD

**Issue by agzam** [Hammerspoon/hammerspoon#1550] opened 2017-09-19 21:46 UTC
Things kinda wacky on my config since the update. One thing I noticed - code that creates `hs.hotkey.new` for `h/j/k/l`, with a modifier (e.g. `alt`) and emits an `eventtap` for `left/down/up/right` (without any modifier) adds all possible modifiers even though I don't want them. Basically I've been using `Alt+h/j/k/l` for arrow keys (for kinda simple Vi mode). Now it stopped working, properly :( Using for example `alt+h` (which I expect to emit `left`) - emits `Ctrl+Shift+Alt+left`

**Comment by asmagill** [comment] 2017-09-19 22:31
Can you post your code or a link to it?  I have  an eventtap in place that lets me use fn-hjkl combinations as arrows and it has been working fine, so I want to see how our approaches differ see what may need to be looked at closer and/or fixed.

**Comment by agzam** [comment] 2017-09-20 18:32
@asmagill I'm afraid it's too much code to post it directly here, here's the point in my config where I do that:
https://github.com/agzam/spacehammer/blob/master/keybindings.lua#L20

It works right after the config loads, but at some point it just stops working, using alt+h/l instead of moving cursor left/right selects words. making it look like it's emitting alt+shift+left/right.

**Comment by agzam** [comment] 2017-09-20 18:44
So, I guess this is what's changed and causing some problems?

> According to Apple Documentation, the proper way to perform a keypress with modifiers is through multiple key events;

**Comment by agzam** [comment] 2017-09-20 20:07
only if I do this before posting the arrow key tap:

    hs.eventtap.event.newKeyEvent(hs.keycodes.map.alt, false):post()
    hs.eventtap.event.newKeyEvent(hs.keycodes.map.shift, false):post()
    hs.eventtap.event.newKeyEvent(hs.keycodes.map.ctrl, false):post()
    hs.eventtap.event.newKeyEvent(hs.keycodes.map.rightalt, false):post()
    hs.eventtap.event.newKeyEvent(hs.keycodes.map.rightshift, false):post()
    hs.eventtap.event.newKeyEvent(hs.keycodes.map.rightctrl, false):post()
    hs.eventtap.event.newKeyEvent(hs.keycodes.map.cmd, false):post()
    hs.eventtap.event.newKeyEvent(hs.keycodes.map.rightcmd, false):post()

    -- and only then
    hs.eventtap.event.newKeyEvent(key, true):post()

it works. so it seems there is a bug. Somehow when triggering arrow key event modifiers get enabled.

**Comment by asmagill** [comment] 2017-09-21 06:51
Just had a chance to review your code; the changes to eventtap to support the "proper" sequencing of events was supposed to be backwards compatible, so I need to run some tests when I have some time tomorrow, but first, just to confirm, this code worked as is in 0.9.55, correct?

The only other thing that jumps out at me is your use of a string for the modifiers; usually I use the original table style versions (e.g. instead of `"alt+shift"`, I'd use `{"alt", "shift"}`... can you try that and let me know if it has any effect? (again, this *shouldn't* have changed, but it isn't the style I usually use, so I wouldn't be surprised if I missed something)

**Comment by asmagill** [comment] 2017-09-23 03:46
Ok, the issue is how the new version of `hs.eventtap.event.newKeyEvent` treats a `nil` as the modifiers argument... in the previous version it was treated as a shortcut for an empty table... now it is treated as a an indicator that any already set flags (through Apple's "preferred" approach) should be left as is and not reset.  Going to have to think about the best way to handle this long term.

In the short term, you can "fix" this by adding `mod = mod or {}` as your first line in the `keyStroke` function in your utils file (before this line https://github.com/agzam/spacehammer/blob/master/utils.lua#L37)

**Comment by asmagill** [comment] 2017-09-23 04:09
Or, you can build Hammerspoon from master... a fix is in place now.

**Comment by cmsj** [comment] 2017-09-26 10:26
Since @asmagill identified and landed a fix, I'm going to go ahead and close this issue.

**Closed by cmsj** 2017-09-26 10:26 UTC
