### ISSUE TITLE
Modal hotkeys and extremely fast key repeats causing CPU spike

### ISSUE THREAD

**Issue by garymh** [Hammerspoon/hammerspoon#248] opened 2015-03-25 22:15 UTC
Hi - I noticed for the last couple of versions, my modal key setups have been causing some big CPU usage in Hammerspoon. Were there any changes recently that are causing this?

I'm using an init.lua that only includes the example from the source:

``` lua
k = hs.hotkey.modal.new({"cmd", "shift"}, "d")

function k:entered() hs.alert.show('Entered mode') end
function k:exited()  hs.alert.show('Exited mode')  end

k:bind({}, 'escape', function() k:exit() end)
k:bind({}, 'J', function() hs.alert.show("Pressed J") end)
```

After using the function a few times, I get the increased CPU usage:

![screen shot 2015-03-25 at 5 01 08 pm](https://cloud.githubusercontent.com/assets/235202/6836659/3147a174-d312-11e4-8b7a-0567ad496867.png)

**Comment by cmsj** [comment] 2015-03-29 06:28
Hmm, I'm not able to reproduce this. When it's in that state, could you bring up the inspector in Activity Monitor and sample the process? I'd like to see if we can figure out what Hammerspoon is doing.

Also, are you able to reproduce it with just that config? Or are you triggering something else in your modal state?

**Comment by garymh** [comment] 2015-03-29 21:13
Hi @cmsj - yep, I can reproduce it with just that config. Entering and then exiting the modal mode starts the CPU increase for me. Here are my inspector windows after:

![screen shot 2015-03-29 at 4 10 29 pm](https://cloud.githubusercontent.com/assets/235202/6887752/7bb3de84-d62e-11e4-8608-0cd85f32e9b8.png)

![screen shot 2015-03-29 at 4 10 36 pm](https://cloud.githubusercontent.com/assets/235202/6887753/7bbff138-d62e-11e4-98ef-dda7b026c554.png)

**Comment by cmsj** [comment] 2015-03-31 09:52
@garymh I just heard from another user who is seeing high CPU usage with modal hotkeys and we tracked it down to his keyboard repeat settings:

10:44:12 <markvilla> defaults write NSGlobalDomain InitialKeyRepeat -int 8
10:44:18 <markvilla> defaults write NSGlobalDomain KeyRepeat -int 0

Are you doing something similar?

**Comment by garymh** [comment] 2015-03-31 12:16
@cmsj That seemed to work! I had InitialKeyRepeat unset (I think it was at the default), but KeyRepeat was at 0. I just moved the sliders in the keyboard settings and tried the modal keys again and the CPU stayed low. 

The values now are:
InitialKeyRepeat = 120
KeyRepeat = 60

Thanks so much for the help!

**Comment by cmsj** [comment] 2017-09-05 16:14
I'm going to close this issue out because it doesn't seem to be getting any traction. Anyone please feel free to re-open it if you want to work on this :)

**Closed by cmsj** 2017-09-05 16:14 UTC
Labels: bug
