### ISSUE TITLE
Hammerspoon 0.9.79

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2443] opened 2020-09-01 06:52 UTC
Following on from the discussion [here](https://github.com/asmagill/hs._asm.axuielement/issues/22), things I'd love to see included in the next Hammerspoon release are:

- [x] [`hs.websocket`](https://github.com/Hammerspoon/hammerspoon/pull/2293)
- [x] [`hs.axuielement`](https://github.com/Hammerspoon/hammerspoon/pull/2373)
- [x] [`hs.serial`](https://github.com/Hammerspoon/hammerspoon/pull/2397)

**Comment by asmagill** [comment] 2020-09-02 02:26
Ok, I've confirmed that the `hs.axuielement` pull matches the most recent code in the standalone repository, so that is ready for merging whenever.

I've reviewed `hs.serial` and it looks like it contains everything I was concerned about, so no issues with it being included as well.

Where did we leave `hs.websocket`? Did we ever figure out how to allow Hammerspoon to be both a receiver and a sender at the same time with the new pod, or did we decide to pass on that for now? I'm fine with either, as long as the documentation makes clear which.

Both `hs.websocket` and `hs.serial` included cocoa-pods, so I'm a little leery of merging them myself, as I think I recall someone mentioning that a cocoa pod update would be required as part of the process... and since all three of these make changes to `project.pbxproj`, there is going to have to be some manual merging or refactoring of the pulls...

@cmsj, you've usually handled this in the past, but I know your free time is tighter then before... if you want me to handle it, just let me know what I need to do regarding the pods -- I've handled manual merges before and while I dislike them, I know what's involved and what to watch out for.

**Comment by latenitefilms** [comment] 2020-09-02 05:28
`hs.websocket` only acts as a client. I've left `hs.http.websocket` in there, so people can still use it - keeping in mind it's been an undocumented inclusion up until this point anyway - so I doubt many people are actually using it.

To fix the issues in `hs.http.websocket`, I'll need to fork `CocoaHTTPServer`, make the necessary changes in there, then update the pod spec. It's on my list of things to do, but it's been pretty low priority, as `hs.websocket` currently solves all my issues.

You can just run `pod update` from the Hammerspoon directory to update all the pods. I don't think the merging will be too painful, as I don't think there'll be many/any conflicts in the main Xcode project.

**Comment by asmagill** [comment] 2020-09-02 06:18
Do I need to install anything to have access to the `pod` command?

**Comment by latenitefilms** [comment] 2020-09-02 06:21
You can use `gem` to install Cocoapods:

`sudo gem install cocoapods`

See: https://guides.cocoapods.org/using/getting-started.html#installation

**Comment by dasmurphy** [comment] 2020-09-07 10:15
May be someone should be creating a project with the version number here: https://github.com/Hammerspoon/hammerspoon/projects

What do you think?

**Comment by asmagill** [comment] 2020-09-19 07:26
Crap, just remembered I need to regenerate the lua docs json file now that we're using 5.4... it has been a while, but if I recall it was pretty much automated if I can just find the script I used...

@cmsj I know you're otherwise busy, so on the off chance you were almost ready to create the release, I'll try to get it done tonight/tomorrow. I'll post here when it's done.

**Comment by asmagill** [comment] 2020-09-19 08:31
Ok, pull added but I want to spot check it some more before merging.

**Comment by latenitefilms** [comment] 2020-09-19 09:12
In case it helps @cmsj & @cmsj , here's a list of all the changes to date:

> **New Extensions:**
> - Added `hs.axuielement`.
> - Added `hs.serial`.
> - Added `hs.websocket`.
> 
> **New Features:**
> - Added `hs.screenRecordingState()`.
> - Added `hs.window.list()`.
> - Added `hs.pasteboard.watcher()`.
> - Added `hs.relaunch()`.
> - Added `hs.coroutineApplicationYield()`.
> - Added `hs.math.isNaN`,` hs.math.isFinite`, and `hs.math.isInfinite`.
> - Added `hs.chooser:invalidCallback()`.
> - Added `hs.fs.urlFromPath()`.
> 
> **Changes:**
> - We now use Sentry.io instead of Crashlytics for monitoring crash data. 
> 
> **Improvements:**
> - Hammerspoon is now Lua `coroutine` friendly.
> - `hs.streamdeck` has been refactored to add support for the Stream Deck XL and Stream Deck Mini.
> - Added ability to pass optional alert message in Spoon hotkey bindings.
> - Changed `hs.watchable` to allow for a `nil` (or not provided) callback for cleaner watcher construction.
> - The `MJConfigFile` preferences option now resolves symlinks.
> - Added `hs.canvas.useCustomAccessibilitySubrole()`, which allows you to use a standard accessibility subrole for `hs.canvas`.
> 
> **Bug Fixes:**
> - Fixed potential memory leak in `hs.eventtap.event:getUnicodeString()`
> - `hs.chooser` now correctly shows icons in their original colors.
> - Fixed potential crashes due to dispatches in various modules: `hs.application`,` hs.battery.watcher`, `hs.caffeinate.watcher`, `hs.canvas`, `hs.dialog`, `hs.host.locale`, `hs.http`, `hs.httpserver`, `hs.image`, `hs.keycodes`, `hs.location`, `hs.network`, `hs.noises`, `hs.screen`, `hs.socket.udp`, hs.spaces.watcher`, `hs.webview` and `hs.wifi`.
> - `hs.dialog.chooseFileOrFolder()` now supports filenames with space.
> - Fixed bug which allows sending binary data with `hs.socket.udp()`.
> - Fixed bug in `hs.webview.toolbar`, which could cause a delay.
> - Minor bug fixes to `hs.caffienate` and `hs.canvas`.
> - Fixed a potential crash in the `hs.midi` callback.
> - Fixed a potential crash in `hs.settings`.
> - Fixed potential nil error in `hs.window.focus()`

It's gonna be a big release!

**Comment by cmsj** [comment] 2020-09-19 18:52
@asmagill @latenitefilms I super appreciate you guys doing all this work to get a release ready. I should have some time tomorrow between 4pm and 6pm UK time, and then during the week I'll be more flexible, whenever you're ready to go.

**Comment by asmagill** [comment] 2020-09-19 19:17
@cmsj, I'd like to see #2471 and #2468 land, and I'd like your thoughts re #2426, but otherwise I think anything else I'm working on can wait for the subsequent release.

I want to poke at the updated docs a little more before landing, but unless there are objections, I plan to do so tonight (Central US time) so fingers crossed tomorrow afternoon UK time should be fine, if your schedule permits... but don't rush things if later in the week ends up working out better -- either is good.

**Comment by latenitefilms** [comment] 2020-09-20 00:16
@asmagill - Remind me... what's the status on `hs.text`? Is that almost ready to merge too? We're using version 0.1.1 in CommandPost.

**Comment by asmagill** [comment] 2020-09-20 01:08
Re `hs.text` I want to hold it for 0.9.80... I still want to finish the regex submodule and, since it's been a while and I don't remember all of the particulars, I think I still had some concerns with encoding auto-detection under some conditions... it was returning more false positives than I thought it should for truly random binary data and I still haven't fully determined if this is an artifact of macOS's optimism when using encoding translators (i.e. the mere fact that we choose to use the NSString class is causing it to bend over backwards to try) or if I have maybe implemented something slightly wrong.

**Comment by asmagill** [comment] 2020-09-20 06:05
Ok @cmsj, as far as I am aware, we are ready when you are. Travis of course still hates me and everything I stand for, but since the error occurred during the test phase and not the build phase, I consider this ready for your tests on your build machine as you've mentioned before that those seem to run more reliably.

**Comment by cmsj** [comment] 2020-09-20 09:43
@asmagill I see #2471 and #2468 merged. For #2426 I don't think we should block the release - that one will probably take a while to shake out and check everything.

I'll pull the latest master now and run the tests locally, see how that shakes out

**Comment by latenitefilms** [comment] 2020-09-20 11:42
To avoid confusion, you should probably comment out the:

`2020-09-20 21:06:55: 21:06:55 ERROR:   LuaSkin: Unable to fetch NSRunningApplication for pid: 25464`

...error messages for release.

**Comment by cmsj** [comment] 2020-09-20 16:54
And we're released :)

**Comment by cmsj** [comment] 2020-09-20 16:54
Thanks again, very much, @asmagill and @latenitefilms

**Closed by cmsj** 2020-09-20 16:54 UTC
