### ISSUE TITLE
Dock Icon not hidden

### ISSUE THREAD

**Issue by electrovir** [Hammerspoon/hammerspoon#291] opened 2015-05-15 16:40 UTC
I've deselected "Show dock icon" in Hammerspoon Preferences but the dock icon persists.  Visibility for the menu icon works as expected.

I've even tried using the console.  After calling hs.dockicon.hide(), hs.dockicon.visible() returns false but the icon is still there in the dock.

I'm running OS X 10.8.5.

**Comment by electrovir** [comment] 2015-05-15 17:01
I just did some looking online and found a way around it.
I added
```
<key>LSUIElement</key>
<true/>
```
to Hammerspoon's Info.plist file.  This works.  But you know, I would still expect previously mentioned problem to get patched :P

**Comment by asmagill** [comment] 2015-05-15 17:16
It works for me:

> hs.dockicon.visible()
-- Loading extension: dockicon
true

> hs.dockicon.hide()


> hs.dockicon.visible()
false

> hs.dockicon.show()


> hs.dockicon.visible()
true

My first thought would be to check that Hammerspoon is checked in System Preferences -> Security & Privacy -> Privacy -> Accessibility... if that is correct, then I don't know... Maybe someone else knows what else might affects this?

**Comment by electrovir** [comment] 2015-05-15 18:50
Note, after altering the info.plist file like I did and logging out then back in, system security thought it was damaged and wouldn't let it launch at login (but manually opening it afterwards works fine).

I've been a little bit confused about the enabling Accessibility thing.  When I launched Hammerspoon for the first time it said "Accessibility is enabled. You're all set!" and it still says that.

**Comment by asmagill** [comment] 2015-05-16 03:27
I noticed from your other post, you're running 10.8.5... My tests (and I think most of the primary development team) are mostly on 10.10, however I do sometimes boot off of another drive to test things under 10.8... I'll set aside some time this weekend to do so and see if I can replicate your issue.

**Comment by cmsj** [comment] 2015-05-16 04:33
Thanks @asmagil!

**Comment by asmagill** [comment] 2015-05-16 22:32
Ok, I can confirm that the dock icon does not disappear under 10.8.5, though hs.dockicon.visible() thinks that it has. I'm currently downloading Xcode 5.1 so I can test and debug under Mountain Lion and figure out what might have changed -- I'm pretty sure that this worked correctly with Mjolnir (or at least Hydra) so hopefully I can figure out what's changed by going through the git history and see what might need to be modified again or back…

**Comment by asmagill** [comment] 2015-05-16 22:36
FYI, this was tested with the latest downloaded release version.

**Comment by cmsj** [comment] 2015-05-19 16:45
@asmagill fwiw, MJDockIcon.m hasn't changed since August last year, before we forked

**Comment by asmagill** [comment] 2015-05-19 17:04
Yeah, I figured it probably hasn't changed much... but I am pretty sure I remember it working with 10.8 in one of the iterations... hopefully I can track it down now that I have my 10.8 development drive back online.

**Comment by asmagill** [comment] 2015-06-10 03:29
Ok, according to https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSApplication_Class/#//apple_ref/occ/instm/NSApplication/setActivationPolicy:,  our use of setActivationPolicy to show/hide the dock icon *shouldn't* work since we start the application in the `NSApplicationActivationPolicyRegular` state... Hydra started in the `NSApplicationActivationPolicyAccessory` state because of the presence of the `LSUIElement` set to `true` entry in its info.plist file.

Quote:

> Currently, NSApplicationActivationPolicyNone and NSApplicationActivationPolicyAccessory may be changed to NSApplicationActivationPolicyRegular, but other modifications are not supported.

It appears either 10.9+ loosened this up or we're in sort of a limbo, while 10.8 enforces it, because our Info.plist file doesn't have this entry at all.

I'll try and add this element to the plist and see what that does in regards to toggling the icon via the `hs.dockicon.show()` under 10.8 when I can next boot it up and do various test builds.

It may be that merely having the entry but set to false will work... or it may be that we need to set it to true in the plist and then programmatically change it after the app starts if we want to support 10.8+... and even if we decide that 10.9+ is supported with 10.8 being "more or less" supported, I'd like to see if we can confirm that this looser behavior isn't going to disappear on us in the future with an OS update down the road...

**Comment by electrovir** [comment] 2015-07-31 20:01
Any news for this?  Whenever there's an update, I have to open the app and re-insert the key I mentioned earlier into the plist.

**Comment by asmagill** [comment] 2015-07-31 20:09
Honestly, I had forgotten about this until just yesterday when I was making up a checklist of things I want to work on in Hammerspoon... sorry about that!  I'm hoping to get a chance to boot into my 10.8 device later tonight or tomorrow and take a crack at it.

@cmsj do we know if the "loose" behavior of 10.9 and 10.10 wrt to this plist key is still the case in 10.11?  I forget who's testing 10.11 these days...

**Comment by asmagill** [comment] 2015-08-03 00:26
To avoid dealing with changes to the core app that I'm not really sure I understand (since if things worked the way I understand the docs, dock hiding shouldn't be working at all in any version),  I recommend adding the code at https://gist.github.com/asmagill/4998ccee1a95c211844f to your .hammerspoon directory... if you load the file as recommended in the comments, it will check the Info.plist file and edit it for you.

This code does require hs.host.operatingSystemVersion... I don't remember if this is in the latest release or not, but has been applied to the repository, so it will be in the next if it's not already .

**Comment by electrovir** [comment] 2015-08-04 23:30
Very nice!  I hadn't thought of doing that, nor did I realize hammerspoon could do such a thing!
Thank you! :D

**Comment by cmsj** [comment] 2015-09-02 11:55
@asmagill I've got a machine on 10.11 and I've been using Hammerspoon on it quite extensively, and I always have my dock icon hidden.

I think I'll close out this issue, since we're butting up against inconsistencies in Apple's code, which we can't easily workaround.

**Closed by cmsj** 2015-09-02 11:55 UTC
