### ISSUE TITLE
hs.hotkey and hs.hotkey.modal bind method's repeatfn is delayed feeling laggy

### ISSUE THREAD

**Issue by RichardForrester** [Hammerspoon/hammerspoon#1087] opened 2016-11-20 23:43 UTC
```
function repeatfn()
  hs.eventtap.keyStroke({}, 'right')
end

hs.hotkey.bind({}, 'l', nil, nil, repeatfn)
```

Hammerspoon: v 0.9.49 && 0.9.50
OS: MacOS Sierra

The repeatfn is called very slowly and the rate at which it is called does not seem to be influenced by the System Preferences > Keyboard > Key Repeat && Delay Until Repeat. Identical problem with hs.hotkey.modal.

The issue appears in 0.9.49. The behavior appears to have been correct in 0.9.48.

**Comment by cmsj** [comment] 2016-11-21 16:14
This is a duplicate of #1082 - we put in a short delay for reliability reasons, but it'll be possible to override it in the next release. A short term workaround is to use this code in a function of your own:

```lua
function myKeyStroke(modifiers, character)
    hs.eventtap.event.newKeyEvent(modifiers, string.lower(character), true):post()
    hs.eventtap.event.newKeyEvent(modifiers, string.lower(character), false):post()
end
```

(which is all our `keyStroke()` function does, just with a sleep between the two event posts).

**Closed by cmsj** 2016-11-21 16:14 UTC
