### ISSUE TITLE
Screens unnamed on Apple Silicon

### ISSUE THREAD

**Issue by markdrayton** [Hammerspoon/hammerspoon#2663] opened 2021-01-27 18:39 UTC
Hi!

I'm getting `(un-named screen)` for screen names (both internal and external) on my shiny new MacBook Air M1:

```
> for k, v in pairs(hs.screen.allScreens()) do print(k, v) end
2021-01-27 19:33:26: 1	hs.screen: (un-named screen) (0x600000951778)
2021-01-27 19:33:26: 2	hs.screen: (un-named screen) (0x600000951a38)
```

It doesn't matter if my Dell U2713HM is plugged in or not — everything is `(un-named screen)`.

This is on Big Sur 10.1 and Hammerspoon 0.9.82 (5614). I don't have much of an idea of how to debug this myself but I'm definitely willing to guinea pig anything for someone who does.

**Comment by asmagill** [comment] 2021-01-27 19:43
Confirmed. Running in Rosetta mode doesn't change the behavior either, so not sure if it's a M1 thing or a Big Sur thing.

I will have access later today to an Intel laptop running Big Sur and an Intel iMac running Catalina and will test on those to see if we can narrow the specifics.

**Comment by cmsj** [comment] 2021-01-27 19:44
It's got to be an M1 thing, my Intel Big Sur machine reports screen names.

**Comment by cmsj** [comment] 2021-01-27 19:49
I also feel like this isn't the first time this has come up, but there is essentially nothing we can do about it unless there is some other API that can be probed (which there must be, because macOS itself displays screen names in several places). I'd be curious to know what tools like ScreenResX report.

**Comment by asmagill** [comment] 2021-01-27 20:03
I've been having good luck with an IOKit search module as a possible `hs.battery` replacement (it doesn't work on the M1 macs either)... I'll see if it might offer an alternative for screen names as well.

**Comment by markdrayton** [comment] 2021-01-27 20:07
Yes, sorry, should have mentioned that Big Sur on Intel works fine.

**Comment by markdrayton** [comment] 2021-02-04 14:02
Related discussion:

https://developer.apple.com/forums/thread/666383?answerId=650068022#650068022

Unfortunately searching the internets for `IODPDevice` doesn't turn up anything useful 😞

**Comment by dcai** [comment] 2021-02-09 10:25
I'm having the same issue on m1 macbook, hope there will be a solution to this.

**Comment by cmsj** [comment] 2021-02-14 19:31
This should be resolved in the next release.

**Closed by cmsj** 2021-02-14 19:31 UTC
