### ISSUE TITLE
pathwatcher does not handle watched directories being removed&recreated

### ISSUE THREAD

**Issue by yingnierxiao** [Hammerspoon/hammerspoon#1224] opened 2017-02-06 07:52 UTC
if pathwatcher dir is remove and recreate ,watcher is  no trigger，like this :find ${SRCROOT}/../../../coe/assets/res/ -name "*" -exec touch -cm {} \;

**Comment by cmsj** [comment] 2017-02-07 11:21
I'm not sure if we can work around this easily - pathwatcher is just using the underlying Apple filesystem event (FSEvent) API. If anyone has examples of code that can handle a watched directory going away and coming back, I would love to see them :)

**Comment by asmagill** [comment] 2017-03-28 03:48
As I interpret the docs for `FSEvents`, this is expected behavior

Specifically (about one of the flags used with `FSEventStreamCreate`)

> * kFSEventStreamCreateFlagWatchRoot
> Request notifications of changes along the path to the path(s) you're watching. For example, with this flag, if you watch "/foo/bar" and it is renamed to "/foo/bar.old", you would receive a RootChanged event. The same is true if the directory "/foo" were renamed. The event you receive is a special event: the path for the event is the original path you specified, *the flag kFSEventStreamEventFlagRootChanged is set and event ID is zero* [emphasis added].

And (about one of the parameters received by the `FSEventStreamCreate`):

> * eventIds	
> An array of FSEventStreamEventIds corresponding to the paths in the eventPaths parameter.
>
> Each event ID comes from the most recent event being reported in the corresponding directory named in the eventPaths parameter. Event IDs all come from a single global source. They are guaranteed to always be increasing, usually in leaps and bounds, even across system reboots and moving drives from one machine to another. Just before invoking your callback your stream is updated so that calling the accessor FSEventStreamGetLatestEventId() will return the largest of the values passed in the eventIds parameter; if you were to stop processing events from this stream after this callback and resume processing them later from a newly-created FSEventStream, this is the value you would pass for the sinceWhen parameter to the FSEventStreamCreate...() function.

And the `sinceWhen` parameter of `FSEventStreamCreate`:

> * sinceWhen	
> The service will supply events that have happened after the given event ID. To ask for events "since now" pass the constant kFSEventStreamEventIdSinceNow. Often, clients will supply the highest-numbered FSEventStreamEventId they have received in a callback, which they can obtain via the FSEventStreamGetLatestEventId() accessor. Do not pass zero for sinceWhen, unless you want to receive events for every directory modified since "the beginning of time" -- an unlikely scenario.

If you want to watch a root that may be renamed or deleted, you should be watching its parent.

The down side, of course, is if the parent contains a bunch of files and folders you don't care about, you have to filter them out.

You may be able to keep your current watcher paths as is and add code to the Hammerspoon callback which checks to see if the target was one of the root paths... if so, stop the watcher and restart it with the new path... of course this only works for a rename... for a delate and recreation I think you're back to having to watch the parent and filter out what you don't care about.

**Comment by cmsj** [comment] 2017-03-28 07:31
(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)

**Closed by cmsj** 2017-03-28 07:31 UTC
