### ISSUE TITLE
appfinder.windowFromWindowTitlePattern is very slow

### ISSUE THREAD

**Issue by STRML** [Hammerspoon/hammerspoon#497] opened 2015-08-15 14:35 UTC
`appfinder.windowFromWindowTitlePattern` is very slow on latest `0.9.38`. It adds about 4-5 seconds to my config's init time.

Not sure why this is, or if it has something to do with my config. A dump of app:allWindows() lists about 28 items.

This is not a critical issue, but I figured I'd open it in case someone else was googling around. To work around it, I instead grab the application I expect the window title to be under, then cycle through the windows. This is much faster. For example:

```lua
function applyLayout(layout)
  return function()
    alert.show("Applying Layout.")
    for appName, place in pairs(layout) do
      -- Two types we allow: table, which is {appName, windowTitle}, or just the app itself
      if type(appName) == 'table' then
        local parentAppName = appName[1]
        local windowPattern = appName[2]
        local app = appfinder.appFromName(parentAppName)
        if app then
          for i, win in ipairs(app:allWindows()) do
            if string.match(win:title(), windowPattern) then
              applyPlace(win, place)
            end
          end
        end
      else
        local app = appfinder.appFromName(appName)
        if app then
          for i, win in ipairs(app:allWindows()) do
            applyPlace(win, place)
          end
        end
      end
    end
  end
end
```

**Comment by cmsj** [comment] 2015-09-02 12:02
I think this is a duplicate of #233, so I'm closing this issue.

**Closed by cmsj** 2015-09-02 12:02 UTC

**Comment by lowne** [comment] 2015-09-15 10:46
("crossposting" for completeness)
After having updated to 0.9.40 or later,  as soon as you (if you still) notice sluggishness or excessive delay (upon calling `windowHints`, `layout`, etc), please open the Console and run this:
```lua
hs.window._timed_allWindows()
```
(If you get no output, try again a bunch of times (up arrow+return) until you (hopefully) do)

Then please paste the output in issue #233.
