### ISSUE TITLE
Watchers and self-reference and garbage collection

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/hammerspoon#775] opened 2016-02-01 18:09 UTC
Seeing #681 and #774 got me thinking...

If we modify the structures/objects for userdata to include a self-reference for the userdata itself, and set it in the `start` method and unset it in the `stop` method, actually storing the userdata for a watcher which is expected to persist through the entire lifetime of a Hammerspoon run becomes unnecessary... We'd have to be careful to make sure that a stop does clear the reference, so collection can occur as expected when creating a temporary watcher, but for ones that persist for the lifetime of Hammerspoon, this isn't an issue.

This differs somewhat from what we do with hs.drawing, hs.webview, and hs.speech.listener, since we don't want to create the self-reference at creation, but only when the watcher is actually running, but I've been experimenting with this approach in my latest modules, and it seems to work well, as long as the creating and destruction of the self-ref is properly balanced.

Would it be worth modifying the existing watchers to follow this pattern?

**Comment by cmsj** [comment] 2016-02-01 19:44
@asmagill I don't hugely like the idea, because it's somewhat violating the intended behaviour of Lua, however, it feels like a pretty common thing that people are running in to, so maybe we should do it. It would then mean though that we might be surprising a whole other group of people with our behaviour, but at least those people are expecting GC and will be more likely to figure out what's going on.

Overall, I think I have to come down on the side of adding the self-reference.

Either way, I think we should probably be more clear in our documentation for all of our constructors, as to what the lifecycle behaviour is.

(also, it's a shame we're holding on the LuaSkin userdata abstraction PR, that could be fairly trivially enhanced to automatically capture a self-ref for userdata objects, and provide a neat API for removing the ref in `:stop()`/`:delete()` methods :) )

**Comment by lowne** [comment] 2016-04-20 13:02
Just for completeness: an alternative might be to simply to shove the watchers into e.g. `hs._refs` (and unset their entry in `:stop()`), with the additional benefit that don't-mess-with-my-GC users would simply have to add `setmetatable(hs._refs,{__mode='kv'})` to their `init.lua` to restore the "pure" behaviour (this of course could also be properly surfaced as a documented top level variable/function for advanced users)

**Comment by cmsj** [comment] 2016-04-20 14:33
As much as I don't like messing with the concepts of GC in Lua, this is an issue which has continued to come up, and will continue to come up because it's conceptually a bit weird when you're looking at an init.lua in isolation.

So, let's consider the various options here:

 * @asmagill 's suggestion of userdata structs containing a self ref
 * @lowne 's suggestion of a global `_refs` table
 * Address this widely and clearly in the API docs and GSG, rather than in code
 * Other possibilities?

To me, the C solution has a clear advantage that if/when we progress on #747, the self-reffing becomes easier to have happen automagically.

One niggle I have with the @asmagill 's solution relates to retaining/releasing the self-ref on `:start()`/`:stop()`. This seems like it might make the behaviour even more inscrutable, in that you might create a watcher at startup, then go to `:start()` it some time later and discover it's already gone. Or you might create/start it immediately, stop it some time later, then expect to be able to re-start it at some distant point in the future and discover that it's vanished. I wonder if it might not just be better to self-ref at creation time, and add explicit deletion methods.

Sorry, this comment is getting a bit rambly, but this is all making me uneasy - I don't think we're going to find a perfect solution with self-refs. I almost wonder if we should be coming at this from an entirely different angle, and see if we can preserve the locals at the end of init.lua's evaluation. Or maybe we should go with the global hs._refs table and expose it via a module so people can figure out which objects they have created.

In summary... argh :)

**Comment by cmsj** [comment] 2016-04-20 14:35
(or maybe each module which creates objects, should retain its own set of refs, and that table would be exposed by some API common to each module?)

**Comment by lowne** [comment] 2016-04-20 16:54
> see if we can preserve the locals at the end of init.lua's evaluation

That was one of my first thoughts as well, but it'd be an actually "hacky" solution (involving the debug library etc) compared to the simple "store stuff you don't want to lose into a table with the desired GC behaviour".

> and that table would be exposed by some API common to each module?

Not completely relevant, but on that line of thought a common `makeWatcher` might wrap all the required infrastructure in one place:
```lua
-- screen/init.lua
local screen=require'hs.screen.internal'
screen.watcher=hs._makeWatcher(require'hs.screen.watcher')
[...]
return screen
```

**Comment by cmsj** [comment] 2016-04-20 16:59
@lowne the only tricky part of a common `makeWatcher` is that watchers pop up in all sorts of places in the codebase, they're not always neatly delineated into their own watcher submodules.

I think whatever we do, we're going to need to explain how the local scope works in init.lua, but I'm currently thinking that maybe `hs._refs` may be the way to go, but with an explicit documentation entry for every relevant constructor (since this applies to other objects, e.g. `hs.drawing`, as much as it does watchers), saying that this object is exempt from normal Lua garbage collection and must be explicitly destroyed via a `:delete()` or `:destroy()` or something, when the user is done with it.

@asmagill what are your thoughts on this these days?

**Comment by deryni** [comment] 2016-04-20 17:34
I think just documenting that the objects returned by the watcher functions need to be stored in globally reachable variables would go *miles* in helping fix the problem here.

Having a "blessed" location to do that might be nice too (with suggested conventions for using some semi-unique id (module name?) as the key) might help too (just to avoid unnecessary global namespace pollution.

**Comment by asmagill** [comment] 2016-04-20 18:14
First off, I'm against treating `init.lua`'s local variables as some how special... it's just like any other file... and opens up the question of what to do with locals for files included by `init.lua`... via `require`, `dofile`, `loadfile`?  Too many changes to the expected behavior of Lua.

I'm leaning towards the `hs._refs` idea... as stated above, the entire thing can be "disabled" by changing it's mode, and if it works something like `hs._refs[userdata] = true`, then someone who knows what they are doing can exempt a single specific case with a single `hs._refs[userdata] = nil` after the userdata is captured locally (or even `hs._refs[constructorfunction()] = nil` if you truly don't even want to capture it locally).

The idea of capturing a self-ref in the Objective-C side still has a place, though maybe not for all objects/watchers... if the Objective-C object should persist even after it goes out of reference on the Lua side (i.e. if it's useful/functional/helpful without Lua needing to keep track of it), then the C-side self-ref makes sense. If the Objective-C object has no purpose once Lua gives up on it, then the self-ref shouldn't be kept... Lua semantics (and there may be a learning curve for some in understanding what those are) should be honored...  I think better documentation and `hs._refs` is probably the best balance between the two since it only requires one additional line of Lua code to exempt a specific object.

**Comment by cmsj** [comment] 2016-04-20 18:31
ok, so it seems like we're all leaning towards an `hs._refs`. Should we maybe wrap it in a thin abstraction layer (so, just a few functions for add/remove/query/list the refs table), in case we need to change the implementation later (because this is going to be exposed to users).

**Comment by cmsj** [comment] 2017-09-05 16:10
@asmagill Do you see this going anywhere? I don't have time to work on it, and it would be quite a bit of work. If not, let's close the issue and just wish we'd done this from the start ;)

**Closed** 2018-04-04 13:47 UTC
Labels: enhancement, needs-response
