### ISSUE TITLE
Crash in config after update to 0.9.96, in spaces.lua

### ISSUE THREAD

**Issue by evanmoses-okta** [Hammerspoon/hammerspoon#3174] opened 2022-03-29 23:15 UTC
After updating to 0.9.96, I get this error, in a previously-working init:

```
2022-03-29 16:10:59: -- Loading extensions: window.filter
2022-03-29 16:10:59: -- Some applications have alternate names which can also be checked if you enable Spotlight support with `hs.application.enableSpotlightForNameSearches(true)`.
2022-03-29 16:10:59: *** ERROR: ...merspoon.app/Contents/Resources/extensions/hs/spaces.lua:71: attempt to index a nil value (local 'contents')
stack traceback:
	...merspoon.app/Contents/Resources/extensions/hs/spaces.lua:71: in local 'getDockExitTemplates'
	...merspoon.app/Contents/Resources/extensions/hs/spaces.lua:76: in main chunk
	[C]: in function 'rawrequire'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: in function 'require'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1530: in main chunk
	[C]: in function 'rawrequire'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: in function 'require'
	(...tail calls...)
	[C]: in function 'rawrequire'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: in function 'require'
	...merspoon.app/Contents/Resources/extensions/hs/window.lua:1027: in function <...merspoon.app/Contents/Resources/extensions/hs/window.lua:1025>
	(...tail calls...)
	/Users/<redacted>/.hammerspoon/init.lua:190: in main chunk
	[C]: in function 'xpcall'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:723: in function 'hs._coresetup.setup'
	(...tail calls...)
```

line 190 in my config looks like
```
local wf = hs.window.filter
```

**Comment by asmagill** [comment] 2022-03-30 00:00
Can you check to see if the new build referenced at https://github.com/Hammerspoon/hammerspoon/issues/3170#issuecomment-1082420854 fixes your issue?

**Comment by chinleo** [comment] 2022-03-30 08:16
> Can you check to see if the new build referenced at [#3170 (comment)](https://github.com/Hammerspoon/hammerspoon/issues/3170#issuecomment-1082420854) fixes your issue?

It fixed 👍🏻

**Comment by cmsj** [comment] 2022-03-30 10:07
Closing as a duplicate of #3170

**Closed by cmsj** 2022-03-30 10:07 UTC
