### ISSUE TITLE
Crash - MJConsoleWindowController.m line 139

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2040] opened 2019-02-22 09:38 UTC
See: http://crashes.to/s/b9927e59805

Code in question:

```
- (void) appendString:(NSString*)str type:(MJReplLineType)type {
    NSColor* color = nil;
    switch (type) {
        case MJReplLineTypeStdout:  color = self.MJColorForStdout; break;
        case MJReplLineTypeCommand: color = self.MJColorForCommand; break;
        case MJReplLineTypeResult:  color = self.MJColorForResult; break;
    }

    if (type == MJReplLineTypeStdout) {
        str = [NSString stringWithFormat:@"%@: %@", [self.dateFormatter stringFromDate:[NSDate date]], str];
    }

    NSDictionary* attrs = @{NSFontAttributeName: self.consoleFont, NSForegroundColorAttributeName: color};
    NSAttributedString* attrstr = [[NSAttributedString alloc] initWithString:str attributes:attrs];
    [[self.outputView textStorage] performSelectorOnMainThread:@selector(appendAttributedString:)
                                       withObject:attrstr
                                    waitUntilDone:YES];
}
```

@cmsj - Maybe some further code is needed to make sure `str` and `type` are valid?

**Comment by cmsj** [comment] 2019-03-04 09:47
Is this reproducible somehow?

**Comment by latenitefilms** [comment] 2019-03-04 09:55
No, unfortunately not - Crashlytics has only reported it once.

Feel free to close this issue if there's not enough information to go on.

**Comment by asmagill** [comment] 2019-03-28 04:36
FWIW, if `type` were out of bounds, I'd have expected the error to be with line 135 and not 139 (as reported by Crashlytics)... while setting a dictionary key's value to `nil` clears it when it's a mutable dictionary, I'm not 100% positive that works in the dictionary initializer (especially as it's *not* mutable), so it might be worth giving `color` a default value or checking it before assigning it to the dictionary.

The header for NSAttributedString declares `NS_ASSUME_NONNULL_BEGIN`, so `str` being `nil` might be the cause, though I'd expect it to fail a little closer to the Hammerspoon line and not 13 calls deeper... but what do I know about Apple's Foundation internals?

I think this is a rare edge case (or we'd see it more often) but easy enough to check for, assuming it's not one of those really bizarre situations where certain UTF8/16 sequences were causing applications to crash like a couple of years ago (though last I heard Apple had corrected for all of the known cases)

I'll see if I can make a pull request later tonight/tomorrow.

**Comment by latenitefilms** [comment] 2019-03-28 04:50
FYI: Because this crashed in CommandPost, not Hammerspoon, it's possible that I might have made a code change somewhere along the lines so the line numbers might be slightly off than what you'd be thinking if you're referring to Hammerspoon source. I try to keep CommandPost & Hammerspoon in sync for the most part, but sometimes I merge things into CommandPost earlier than it makes it into the Hammerspoon main branch.

**Comment by cmsj** [comment] 2019-03-28 22:10
the color now gets a default value, and the string is checked for nilness.

**Comment by cmsj** [comment] 2019-03-28 22:11
Derp, messed up the `Closes` commit message. This was done in 05fd6e97

**Closed by cmsj** 2019-03-28 22:11 UTC
