### ISSUE TITLE
Messages App windows do not have proper geometry when fetched from a filter 

### ISSUE THREAD

**Issue by zmanji** [Hammerspoon/hammerspoon#2487] opened 2020-09-21 22:59 UTC
On the latest Hammerspoon release `0.9.80` windows from the Messages app no longer have geometry, role or subrole set. Other properties might be invalid as well.

To reproduce do the following:
1. If running already, kill the Messages app process.
2. In the Hammerspoon Console create a window filter for the app with `f = hs.window.filter.new("Messages")`
2. Launch the messages app.
3. Observe that running `f:getWindows()[1]:frame()` in the console returns the correct geometry
3. Close the messages window with cmd-w
4. Open the messages window again.
5. Run `f:getWindows()[1]:frame()` again and observe the geometry is 0,0,0,0 even though the window is open and running.

This does not occur on a previous release `0.9.78`

**Comment by asmagill** [comment] 2020-09-22 04:21
I am unable to replicate this issue with the outline you specified... to get behavior you describe I have to do something like the following:

~~~lua
> f = hs.window.filter.new("Messages")

-- now launch Messages app

> fw = f:getWindows()[1]

> print(fw:frame(), fw:role(), fw:subrole())
hs.geometry.rect(696.0,338.0,730.0,516.0)	AXWindow	AXStandardWindow

-- now go to Messages and close window, then re-open by clicking on it in the Dock

> print(fw:frame(), fw:role(), fw:subrole())
hs.geometry.unitrect(0.0,0.0,0.0,0.0)		

-- but if I re-assign fw again first:

> fw = f:getWindows()[1]

> print(fw:frame(), fw:role(), fw:subrole())
hs.geometry.rect(696.0,338.0,730.0,516.0)	AXWindow	AXStandardWindow
~~~

If this latter is closer to what you're trying to do, the issue is that when the window is opened again, it is a brand new window -- the original object is no longer valid.

OTOH, if the above is *not* closer to what you're doing, then I have no idea... is what you describe the actual steps you have taken manually in the console, or is it an approximation of a script that isn't working for you?

**Comment by asmagill** [comment] 2020-09-22 04:23
(I should note that I do not have #2485 applied to my local build of Hammerspoon)

**Comment by zmanji** [comment] 2020-09-22 11:32
Unfortunately this is a rough approximation of what I was trying to do for this bug report.

I think a better reproduction would be:
1. If running kill the messages app.
2. In the Hammerspoon Console create a window filter like so:
```
filter = hs.window.filter.new(function (w)
  return w:isStandard() and (w:application():title() == "Messages")
end)
```
3. Open and close the messages app window a few times
4. Run `#filter:getWindows()` to see how many windows are matched by the window filter after the above step

On `0.9.78` `#filter:getWindows()` returns 1 when the messages window is open and 0 when it is closed as expected.
On `0.9.80`  `#filter:getWindows()` returns 0 when the messages window is open and 0 when it is closed.

For now I have downgraded `0.9.78` and I will use `git bisect` to update this bug with more details by hopefully finding the first commit where this issue was introduced.

**Comment by zmanji** [comment] 2020-09-22 17:15
With my above reproducer and git bisect, I looked at all of the changes between `0.9.78` and master. Unfortunately due to some build issues with some commits on master, I was forced to run `git bisect skip` a few times. This is the full `git bisect log` with the above reproducer:
```
git bisect start
# bad: [a739ec90ec451ef957ed880e8c3481fa9bd33e09] Add sentry release finalisation to librelease.sh
git bisect bad a739ec90ec451ef957ed880e8c3481fa9bd33e09
# good: [fec33c322bc559c7099fdaa3e423555876882c76] Prepare for 0.9.78
git bisect good fec33c322bc559c7099fdaa3e423555876882c76
# bad: [f1230dd654c5f0bb004fd19bd13f977abbce8480] Merge remote-tracking branch 'Hammerspoon/master'
git bisect bad f1230dd654c5f0bb004fd19bd13f977abbce8480
# good: [48f3090209f8240eadce217d1f77659e770e8436] adding coroutine based application yield helper
git bisect good 48f3090209f8240eadce217d1f77659e770e8436
# bad: [9c9ad75bafb72afd7bc417e5473faf7542c7c6d1] Enhance previous logging changes
git bisect bad 9c9ad75bafb72afd7bc417e5473faf7542c7c6d1
# bad: [bc707cb3fb86a38334c4db643e25d781ad297e53] Tweak hs.application testFrontmostApplication to probe a failure
git bisect bad bc707cb3fb86a38334c4db643e25d781ad297e53
# bad: [442f0181fba8f61129457cd562644c82e836279a] Fix up some tests and make the build token detection more flexible, so it can work reliably in an xcode server bot
git bisect bad 442f0181fba8f61129457cd562644c82e836279a
# skip: [115dc37b6814f0934abc7c6b9532a59132928077] Attempt to keep this working
git bisect skip 115dc37b6814f0934abc7c6b9532a59132928077
# bad: [d3d8561669073785249de722cef544dba91bb20c] Fix
git bisect bad d3d8561669073785249de722cef544dba91bb20c
# skip: [4698dc669775fa85c3f55612805f9dc34c7ad19e] Move Lua-originated object methods to the correct metatables
git bisect skip 4698dc669775fa85c3f55612805f9dc34c7ad19e
# bad: [fd9d29deb29b5e86e615c89978d4d803a46b8e21] Refactor HSapplication, HSuielement, HSuielementWatcher and HSwindow out into a separate file so they don't generate build-time circluar dependencies on each other, instead they are now linked into the core HS binary, which is unfortunate, but will do for now
git bisect bad fd9d29deb29b5e86e615c89978d4d803a46b8e21
# skip: [1394adfcca120ac595431f8045fafc79059f0aa0] Fix many many things
git bisect skip 1394adfcca120ac595431f8045fafc79059f0aa0
# skip: [7e4c65fa79ce6f201c90ec8dc4239c9aa2547e6a] Move a couple of hs.application functions to the right module table
git bisect skip 7e4c65fa79ce6f201c90ec8dc4239c9aa2547e6a
# skip: [837ece90d68f3deb07c0f157e6ec8719c741b5e6] Add some more HSwindow methods and resolve cyclical type definitions
git bisect skip 837ece90d68f3deb07c0f157e6ec8719c741b5e6
# skip: [31d02fbb3b63fb2d36d32efe8521f66dec1dbb7f] Modernise hs.application, hs.window and hs.uielement
git bisect skip 31d02fbb3b63fb2d36d32efe8521f66dec1dbb7f
# only skipped commits left to test
# possible first bad commit: [fd9d29deb29b5e86e615c89978d4d803a46b8e21] Refactor HSapplication, HSuielement, HSuielementWatcher and HSwindow out into a separate file so they don't generate build-time circluar dependencies on each other, instead they are now linked into the core HS binary, which is unfortunate, but will do for now
# possible first bad commit: [115dc37b6814f0934abc7c6b9532a59132928077] Attempt to keep this working
# possible first bad commit: [7e4c65fa79ce6f201c90ec8dc4239c9aa2547e6a] Move a couple of hs.application functions to the right module table
# possible first bad commit: [4698dc669775fa85c3f55612805f9dc34c7ad19e] Move Lua-originated object methods to the correct metatables
# possible first bad commit: [1394adfcca120ac595431f8045fafc79059f0aa0] Fix many many things
# possible first bad commit: [837ece90d68f3deb07c0f157e6ec8719c741b5e6] Add some more HSwindow methods and resolve cyclical type definitions
# possible first bad commit: [31d02fbb3b63fb2d36d32efe8521f66dec1dbb7f] Modernise hs.application, hs.window and hs.uielement
```

Unfortunately the skipped commits are not buildable locally for me, so I am unable to dive deeper. However I can confirm the most recent commit on master where the above reproducer works as expected is fbcf5400b8140db11cfde5a0941a434a37406d9c which is just before 31d02fbb3b63fb2d36d32efe8521f66dec1dbb7f

I see the author of all of those commits is @cmsj perhaps they would be able to comment further?

For now I can stay on an older version of hammerspoon but from the reproducer above, which I have done extensively now, it seems that whatever is powering the window filter, is missing events involving the Messenger.app window because after the window is re-opened, the filter doen't pick up on it.

**Comment by zmanji** [comment] 2020-09-22 17:22
@asmagill @szymonkaliski if I apply #2485 locally, then the simplified reproducer works just fine.

**Comment by asmagill** [comment] 2020-09-22 17:34
Oddly, I still can't reproduce what you describe with your simplified version, but I'll take your word for it that #2485 fixes it. Planning to land #2485 later today after ensuring it doesn't interfere with some other pending updates.

**Comment by asmagill** [comment] 2020-09-22 22:24
#2485 has landed.

**Closed** 2020-09-23 10:57 UTC
