### ISSUE TITLE
[Request] Ability to have hs.menubar items retain their same position upon startup/hs.reload (or at least next to the "main" Hammerspoon menubar item) rather than always reverting back to the left-most item 

### ISSUE THREAD

**Issue by dmattera** [Hammerspoon/hammerspoon#2878] opened 2021-05-18 14:01 UTC
Not sure this is even possible given the way Hammerspoon utilizes the APIs for hs.menubars/how the system behaves but just thought I'd raise the question. This is something that would benefit me and my personal workflow quite significantly as I utilize multiple hs.menubar items heavily and have a lot of non-HS items which means they aren't all always visible and so every time I reload, I have to move them all back to an always-visible section of menubar one by one.

Steps to reproduce:

1. Create and show a new hs.menubar item
2. Said menubar item will be placed at the end (left-most side) of all the existing menubar items
3. Cmd+click/drag the new item to a new position in the menubar
4. Perform hs.reload() or restart Hammerspoon enitrely
5. The hs.menubar item is placed back at the end of existing menubar items (unlike the "main" Hammerspoon menubar which, if you restarted Hammerspoon enitrely, will return to the position it occupied before the restart)

**Comment by DemoorBug** [comment] 2021-11-19 06:05
Same problem, it resets to the leftmost side every time it starts, very annoying

**Comment by jeffheartmp** [comment] 2022-04-21 20:43
bump on this!

**Comment by latenitefilms** [comment] 2022-04-21 21:18
This might be helpful?

https://github.com/shergin/NSStatusBar-MISSINGOrder

**Comment by latenitefilms** [comment] 2022-04-21 22:14
Maybe the issue is as simple as just not supplying the menubar items an autosavename?

https://developer.apple.com/documentation/appkit/nsstatusitem/1644022-autosavename

**Comment by latenitefilms** [comment] 2022-04-22 02:10
My guess is that it'll most likely fix things, as without an `autosaveName`, it won't be able to keep track of user-created menubar items. I'll try test it out today.

**Comment by latenitefilms** [comment] 2022-04-22 10:10
I've just added a pull request (#3195) which seems to do the trick.

**Comment by jeffheartmp** [comment] 2022-04-22 16:07
Hey @latenitefilms thank you for doing this, really cool stuff. 

I checked out your branch and compiled Hammerspoon in Xcode, then updated my code to this: 

```
caffeine = hs.menubar.new()
function setCaffeineDisplay(state)
    --add the position on each click
    caffeine:autosaveName('caffeine');
    
    if state then
        caffeine:setTitle("U")      
    else 
        caffeine:setTitle("D")
    end
end```

After I move the icon, I click it to trigger the autosaveName method.

But after I reload hammerspoon, it shoots back to the left again. 

Any ideas?

**Comment by latenitefilms** [comment] 2022-04-22 18:08
Try setting the autosaveName when creating the menubar instead, as opposed to using the autosaveName method. I might need to tweak the method if it's not working as intended.

**Comment by latenitefilms** [comment] 2022-04-22 21:54
I've just pushed a fix for the `hs.menubar:autosaveName()` method.

Here's some example code for testing:

```lua
a = hs.menubar.new(true, "A"):setTitle("A")
b = hs.menubar.new(true, "B"):setTitle("B")
c = hs.menubar.new(true):autosaveName("C"):setTitle("C")
z = hs.menubar.new(true):setTitle("Z") -- this won't save position
```

To test, run the above code in the Console, change the menubar icon positions, restart Hammerspoon, then run the code again.

**Comment by jeffheartmp** [comment] 2022-04-23 14:28
When I try to build the hammerspoon app in Xcode I get this error: 

> WARN: Function/Method/Constructor description for hs.menubar:autosaveName([name])  should be a single line. Other content may belong in the Notes: section.

**Comment by jeffheartmp** [comment] 2022-04-23 14:38
> I've just pushed a fix for the `hs.menubar:autosaveName()` method.
> 
> Here's some example code for testing:
> 
> ```lua
> a = hs.menubar.new(true, "A"):setTitle("A")
> b = hs.menubar.new(true, "B"):setTitle("B")
> c = hs.menubar.new(true):autosaveName("C"):setTitle("C")
> z = hs.menubar.new(true):setTitle("Z") -- this won't save position
> ```
> 
> To test, run the above code in the Console, change the menubar icon positions, restart Hammerspoon, then run the code again.

This worked on the last build that I made, thank you for the fix!

**Comment by latenitefilms** [comment] 2022-04-23 21:49
Opps - I've fixed the documentation bug. Thanks!

**Closed** 2022-04-23 22:45 UTC

**Comment by msanders** [comment] 2023-11-21 02:21
This no longer seems to work in Hammerspoon 0.9.100.

```
> c = hs.menubar.new(true):autosaveName("C"):setTitle("C")
[string "c = hs.menubar.new(true):autosaveName("C"):se..."]:1: method 'autosaveName' is not callable (a nil value)
```

I tried a few different ways to hide/unhide a menubar item while the app is running but it doesn't seem to be possible currently. E.g.:

```lua
c = hs.menubar.new(true, "C")
c:removeFromMenuBar()
c:returnToMenuBar() -- Doesn't retain position

c = hs.menubar.new(true, "C")
c:delete()
c = hs.menubar.new(true, "C") -- Doesn't retain position
```

The position is saved across launches when the `autosaveName` argument is used in the init function, though.
