### ISSUE TITLE
`application.watcher` stops watching after several times

### ISSUE THREAD

**Issue by arolle** [Hammerspoon/hammerspoon#681] opened 2015-12-11 19:38 UTC
With release 0.9.43 I am testing the `application.watcher`. Depending on complexity/load of the init script, the watcher stops after several executions, hammerspoon still keeps on listening to e.g. keyboard bindings.

Down, an applescript and an `init.lua` is appended to reproduce the issue.
With my personal configuration the watcher stops is after 10 times switching applications. The problem occurs with the appended scripts after 400 times switching applications (yes 40 seconds to reproduce the bug).

``` applescript
-- applescript
repeat 100 times
    tell application "System Events"
        delay 0.1
        key code 48 using command down -- send cmd + tab
    end tell
end repeat
```

``` lua
-- init.lua
hs.application.watcher.new(function(name,event, app) appwatch(name,event,app) end):start()

local i = 1
function appwatch(name, event, app)
  local win = hs.window.focusedWindow()
  if not win then
    print("no window focused")
    return
  end

  local lookuptable = {
    [hs.application.watcher.activated] = "act",
    [hs.application.watcher.deactivated] = "deact",
    [hs.application.watcher.hidden] = "hid",
    [hs.application.watcher.launched] = "lnchd",
    [hs.application.watcher.launching] = "lnchng",
    [hs.application.watcher.terminated] = "term",
    [hs.application.watcher.unhidden] = "unhid"
  }
  print(i .. " event: ".. lookuptable[event] .. "; app: " .. hs.window.focusedWindow():application():title())
  if event == hs.application.watcher.activated then
    i = i+1
  end
end
```

**Comment by mgee** [comment] 2015-12-11 21:32
I can reproduce it using your script. I did some debugging and the events are still received internally. The [call to the callback function](https://github.com/Hammerspoon/hammerspoon/blob/cb78a67223e614e644ce0427bedcbfa1ab97853b/extensions/application/watcher.m#L110) is still made but somehow does not succeed and no error is reported.

@cmsj Any idea?

**Comment by cmsj** [comment] 2015-12-26 14:08
hmm, struggling to reproduce this one, I've run the test script, with 500 iterations and Hammerspoon is calling the appwatch() function each time

**Comment by cmsj** [comment] 2015-12-26 14:11
@mgee if you can reproduce it, we could pepper the Objective C callback method with NSLog() calls to see if there is something going on there, but if it's making the call to protectedCallAndTraceback then this is most mysterious indeed.

**Comment by arolle** [comment] 2015-12-26 14:17
Depending on your machine (the memory?), even more runs could be necessary.

Temporarily I proceeded as follows to solve the issue for me.
```lua
local appwatcher = application.watcher.new(function(name,event, app)
    appwatch(name,event,app)
  end)
  appwatcher:start()

function appwatch(name, event, app)
  appwatcher:stop()
  appwatcher:start()
  -- ...
end
```

**Comment by mgee** [comment] 2015-12-27 11:36
@cmsj I added some NSLog calls and the call to `protectedCallAndTraceback` is made and returns true, hence it should have worked.

**Comment by cmsj** [comment] 2015-12-27 19:01
@mgee interesting, that rather suggests that Lua itself is losing its mind. hmmmm.

**Comment by mgee** [comment] 2016-02-01 17:28
In the initial example the application watcher was not stored in a variable. Then as mentioned in #774 the watcher will be garbage collected at some point.

@arolle can you verify if the bug still exists if the application watcher is stored in a variable?

**Comment by cmsj** [comment] 2016-02-01 17:30
@mgee good catch :)

**Comment by arolle** [comment] 2016-02-02 07:22
Assigning the application watcher to a local variable, as in

```lua
local appwatcher = hs.application.watcher.new(function(name,event,app) appwatch(name,event,app) end):start()
```
will not resolve the issue. Whereas assigning to a (unique name) global variable, makes the watcher persistent among the dozens of tests which I ran,

```lua
-- global variable, unique name
appwatcher = hs.application.watcher.new(function(name,event,app) appwatch(name,event,app) end):start()
```

But garbage collection will anyways remove the – further unreferenced – global variable, stopping the watcher:

```lua
-- init.lua
appwatch = hs.application.watcher.new(function(name,event, app) appwatch(name,event,app) end):start()

local i = 1
function appwatch(name, event, app)
  print(i)
  if i > 9 then
    collectgarbage()
  end
  i = i+1
end
```

**Comment by junkblocker** [comment] 2016-04-18 21:37
This has recently started to happen to me consistently. Any hope of a fix soon?

**Comment by cmsj** [comment] 2016-04-18 21:39
@junkblocker are you capturing your watchers into variables?

**Comment by junkblocker** [comment] 2016-04-18 21:43
My structure is:

```lua
function applicationWatcher(appName, eventType, appObject)
  --
end

local appWatcher = hs.application.watcher.new(applicationWatcher)
appWatcher:start()
```

What's the recommendation?

**Comment by junkblocker** [comment] 2016-04-18 22:20
If I include ``appWatcher`` in ``reloadConfig()`` afterwards, the watcher does stay around and the problem doesn't happen.

**Comment by heptal** [comment] 2016-04-20 06:57
That's because `appWatcher` is local so it goes out of scope and gets garbage collected. You can either remove `local` or, as you've done, reference it somewhere else like in your global `reloadConfig`.

**Comment by asethwright** [comment] 2016-04-30 18:16
@heptal Thanks, worked for me to set it as a global variable.

**Comment by epaga** [comment] 2016-07-20 09:36
Perfect, thanks!

One thought would be to possibly remove the "local" keyword in the application watcher sample code in the getting started guide? This is why it was "local" for me in the first place...I simply had taken that and modified it for my own script.

**Closed** 2017-04-27 14:37 UTC

**Comment by cmsj** [comment] 2017-04-27 16:16
(I've removed the relevant `local` keywords from the GSG. Thanks!)

**Comment by anguskeatinge** [comment] 2025-10-29 10:19
You're a hero @heptal
