### ISSUE TITLE
Grid Positioning and window placement animation issues

### ISSUE THREAD

**Issue by jdtsmith** [Hammerspoon/hammerspoon#290] opened 2015-05-12 01:58 UTC
hs.grid seems to put windows in different places when near the right edge of the screen when the Dock is on that side.  To reproduce in the HS console, drag dock to the RHS, place the console on the right, and:

```lua
win=hs.window.focusedWindow()
g=hs.grid.get(win)
g.x=g.x+1
g.w=g.w-1
hs.grid.set(win,g,win:screen())
```

Notice that the window falls under the Dock.  Move the window manually, and re-run the last set command.  Notice that the window does not return to its former location (in fact getting closer and closer to where it should be).  The issue seems to be tied to the Dock's location.  It also occurs when moving windows to the lower grids when the Dock is at the bottom.  This is on a Retina screen.  

Debugging the simple grid code, this seems to be a problem with win:setFrame() not placing the window where you set it, e.g. for width:

```lua
> win:setFrame({x=876.875,y=23,w=526.125,h=438.5})
> for k,v in pairs(win:frame()) do print(k,v) end
h	439
w	588
x	876
y	23
```

I followed this all the way into `hs.window`'s `internal.m`, and it seems that `window_setsize` refuses to change the size of a window once it is overlapping the dock.  
The Dock in principle should never be overlapped by the window, but once it does, the size refuses to change.  The key problem turns out to be in `hs.window`'s `window_transform`.   This can be reproduced by comparing, for an existing window:

```lua
> win:setFrame({x=876.875,y=23,w=526.125,h=438.5},0)
> win:setFrame({x=876.875,y=23,w=526.125,h=438.5},1)
```

first dragging the window in question away from the Dock before each command is run (you'd need to alter the numbers for your display; this is 1440x900 with a right-side dock).  The 1st (fast, animation-free) version works without incident placing the window up against a right-hand dock, but the 2nd (slow animation) version pulls the window to varying degrees into the Dock region, where its size gets "stuck".  How much depends on animation speed, starting position, etc. If I turn animation off with `window.animationDuration=0` then the problem disappears.   Can't tell if the bug is in `window_transform` or deeper.

**Comment by cmsj** [comment] 2015-09-02 12:05
I think this is a (non-obvious) duplicate of #217 - which is to say that if a window gets close to the dock, it somehow becomes "sticky" and can't easily be resized by small amounts.

**Closed by cmsj** 2015-09-02 12:05 UTC
