### ISSUE TITLE
hs.keycodes.methods() should include com.apple.keylayout.US

### ISSUE THREAD

**Issue by xream** [Hammerspoon/hammerspoon#1022] opened 2016-10-04 15:35 UTC
With tools like [hnakamur/inputsource](https://github.com/hnakamur/inputsource), we can get `com.apple.keylayout.US`, but `hs.keycodes.methods()` does not.

**Comment by asmagill** [comment] 2016-10-04 20:45
It's been a long time since I've looked closely at the `hs.keycodes` source, but have you looked at `hs.keycodes.layouts` and `hs.keycodes.currentLayout`?

~~~lua
> hs.inspect(hs.keycodes.layouts())
{ "U.S.", "Dvorak" }

> inspect(hs.keycodes.currentLayout())
"U.S."
~~~

I'm not entirely sure what the `hs.keycodes.methods` function is supposed to return (I've never used it and it returns an empty table on my machine), but it's querying property `kTISTypeKeyboardInputMode` while the code you refer to is querying for `kTISPropertyInputSourceID`, which appears to be a more formal version of what `hs.keycodes.layouts` and `hs.keycoes.currentLayout` return (property `kTISTypeKeyboardLayout`).

**Comment by xream** [comment] 2016-10-04 20:53
I have two input methods. `com.apple.keylayout.US` for English, `com.apple.inputmethod.SCIM.ITABC` for Chinese.
```
> hs.inspect(hs.keycodes.layouts())
{ "U.S." }
> inspect(hs.keycodes.currentLayout())
"U.S."
```
US is missing:
```
> inspect(hs.keycodes.methods())
{ "Pinyin - Simplified" }
```
Why this is nil?
> inspect(hs.keycodes.currentMethod())
nil
```

**Comment by xream** [comment] 2016-10-04 20:58
If you try any other language, like `com.apple.keylayout.Spanish`. `hs.keycodes.currentMethod()` is always nil. 
Maybe it's because my system local is Chinese? Only Chinese input methods are included in `hs.keycodes.methods()`.

**Comment by asmagill** [comment] 2016-10-04 20:59
Interesting... apparently some of the input methods only set certain properties and not others... Ok, I'll take a closer look tonight at the Text and Input Services API and see about adding support for some of the other properties available.

Yeah, I suspect some of it may be locale based.

**Comment by asmagill** [comment] 2016-10-04 20:59
Make that script, not locale, based.

**Comment by asmagill** [comment] 2016-10-08 06:19
As I understand it (and I welcome corrections since I'm not completely positive about this, but it seems to match my observations), "layouts" are keyboard definitions that just remap the keyboard and don't require a change to the default input method while "methods" are input methods which may include one or more keyboard layouts, but the layouts aren't accessible without the input method.

When you look at the output from `hs.keycodes.layouts()`, it's just reporting keyboard input layouts that don't replace the default input method.  When you look at `hs.keycodes.methods()`, it's listing totally separate input methods... that happen to also remap the keyboard layout... these layouts, however, can't be used without the new input method, so `hs.keycodes.layouts` doesn't see them.

What I have done in pull request #1033 is the following:
* added a new method, `hs.keycodes.currentSourceID()` which will return the current sourceID for the layout or input method that is active.  You can also specify a string as a parameter and if that string matches an enabled layout or input method, the keyboard will switch to that layout/input method.
* added an optional boolean parameter to `hs.keycodes.layouts` and `hs.keycodes.methods` so that if you specify true as the parameter, it will return the source id instead of the localized name of the layouts or methods currently enabled

And I've added some notes to the doc strings that I hope make the differences between layouts and methods a little clearer.

**Comment by cmsj** [comment] 2016-10-27 08:44
@asmagill is right, the underlying OS X input systems have two concepts, Input Methods and Layouts. You'll only see layouts that apply to the current input method.

(I'm going to close this out because I don't think there is any work to be done in Hammerspoon. Please re-open if you disagree!)

**Closed by cmsj** 2016-10-27 08:44 UTC

**Comment by sunyj** [comment] 2017-02-01 09:38
Please re-open this issue.  I'm facing same problem here.  My requirement is simple, just remap a key (let's say 'F12' for example) for input method switching.  I know it's easy to map it with system preference, but I have to do this through hammerspoon because I need this key for other uses.  Anyway, I cannot find a way to implement OSX "switch to previous input method" with Lua script.  The problem is that hs.keycode.currentMethod() returns nil, but hs.keycode.setMethod() returns false on nil or 'nil'.

**Comment by asmagill** [comment] 2017-02-01 18:21
I think you need to use `hs.keycodes.currentSourceID` instead... check out the comment above (https://github.com/Hammerspoon/hammerspoon/issues/1022#issuecomment-252406189)

**Comment by sunyj** [comment] 2017-02-06 00:58
> hs.keycodes.currentSourceID()
2017-02-06 08:57:08: -- Loading extension: keycodes
com.apple.keylayout.US

> hs.keycodes.setMethod("com.apple.keylayout.US")
false

**Comment by asmagill** [comment] 2017-02-07 04:13
Try `hs.keycodes.currentSourceID("com.apple.keylayout.US")`.

The combination of "getter" and "setter" into the same function is a syntactic change from the style of using separate functions like `hs.keycodes.currentLayout` and `hs.keycodes.setCurrentLayout`.

The former approach (combining them) is one we've been leaning towards in newer code, while the later approach is still prevalent in older inherited code... in general I try not to mix them in a single module, but apparently missed this when I added source ID support to the `hs.keycodes` module.

**Comment by sunyj** [comment] 2017-02-09 00:54
Thanks, it works.
