### ISSUE TITLE
0.9.41 -> webview can't be created at negative X,Y coordinates

### ISSUE THREAD

**Issue by bradparks** [Hammerspoon/hammerspoon#578] opened 2015-10-01 16:10 UTC
Hey! I've been playing with the new webview, and think it's awesome... but it seems I can't create it at negative X,Y coordinates which I can do with other drawing things. Note that negative coordinates occur when using multiple monitors, and trying to place things on secondary monitors.

e.g. The following 2 routines are identical, except the x,y values in the rect are negative in the fail case.

```
function showBrowserFails()
  local width = 400
  local height = 200
  local rect = hs.geometry.rect(-100, -100, 100, 200)
  local wv = hs.webview.new(rect)
  local url = "http://www.hammerspoon.org/docs/hs.webview.html#new"
  wv:url(url)
  wv:show()
end

function showBrowserWorks()
  local width = 400
  local height = 200
  local rect = hs.geometry.rect(100, 100, 100, 200)
  local wv = hs.webview.new(rect)
  local url = "http://www.hammerspoon.org/docs/hs.webview.html#new"
  wv:url(url)
  wv:show()
end
```

**Comment by bradparks** [comment] 2015-10-01 16:14
Note: This may be related to #570

**Comment by lowne** [comment] 2015-10-01 18:24
Shouldn't be related to `hs.geometry` at all; anyway fwiw `showBroserFails()` works fine here - the window isn't visible as it's out of bounds, but "application expose" shows it.

**Comment by bradparks** [comment] 2015-10-01 19:17
ahh... so it has been created, but just isn't visible.... I can see it in Expose as well.... but why isn't it showing by default? For example, the following code is identical, except it shows a circle using the drawing api, and it shows up just fine on my 2nd monitor. 

It seems to me that the default state of creating a webview like I'm doing above should show the webview... For me, -100, -100 isn't off screen. It's on my 2nd monitor which is above my primary monitor. Which totally works for the red circle I'm showing

```
function vimouse.showBrowserCircle()
  local rect = hs.geometry.rect(-100, -100, 100, 200)
  local mouseCircle = hs.drawing.circle(rect)
  mouseCircle:setFill(false)
  mouseCircle:setStrokeWidth(7)
  mouseCircle:show()
end
```

**Comment by asmagill** [comment] 2015-10-01 19:44
Changing the size components to 500,500 shows the lower right portion of the window on my screen, so I can confirm that the window does in fact exist.  I'll try again later when I have a two monitor setup available.

I'm going to guess that it has something to do with how the OS decides when window coordinates indicate that it belongs on a different monitor versus when it belongs offset from the current/primary one... I'll take a look at what's different between the window creation portions of hs.webview and hs.drawing tonight and see what pops out... hs.webview inherits much of its low level code from hs.drawing, but there were a lot of changes along the way.

**Comment by lowne** [comment] 2015-10-01 19:54
Might have something to do with z order, here webviews are spawned behind regular windows for some reason.

**Comment by asmagill** [comment] 2015-10-01 20:43
Maybe... I do recall changing a few of the default window parameters because for hs.drawing, the default window was created on top of everything, and since webview has  the asHSDrawing method to allow access to the level changing methods, I figured a more normal level would be a better default... I'll check the code out tonight and run some tests.

In the mean time, Brad, can you try creating the webview somewhere on the main screen and then adding :asHSDrawing():setFrame(hs.geometry.rect(-100, -100, 100, 200)) and let me know if that helps?

FYI (I should add this to the docs at some point):
	:asHSDrawing():setFrame will use hs.drawing's setFrame which doesn't care if the window/panel is actually movable or resizable -- it changes the frame anyways.  :asHSWindow():setFrame honors the webview window/panel attributes as set with :windowStyle.

**Comment by bradparks** [comment] 2015-10-01 23:21
I only have a single monitor going on at home, but it seems like the asHSDrawing makes it work a bit better. When my extension loads, it shows a window right off, and that shows up now even if I put in -100, -100 as the X,Y pos. But if I destroy that webview and try and create it again, it doesnt load correctly for some reason (via keyboard switches)

**Comment by cmsj** [comment] 2017-04-27 14:32
I'm going to close this because I'm gardening the bugs and this has been open for ages with no further discussion, feel free to re-open it if there are specific things you want to do :)

**Closed by cmsj** 2017-04-27 14:32 UTC
