### ISSUE TITLE
Developer procedure

### ISSUE THREAD

**Issue by Habbie** [Hammerspoon/hammerspoon#6] opened 2014-10-10 11:56 UTC
Normal users ('the 99%') will make do with the modules we include, and will not have to bother with brew or rocks or whatever.

For the rest, being developers, and users who want beta stuff, we need to document how to submit and how to use third party mods. Probably comes down to how Mjolnir works right now for all modules.

**Comment by bradparks** [comment] 2015-09-18 15:30
I'd like to do a new pure lua extension. Do I have to rebuild the app in XCode every time I want to test my extension? Or can I just drop it in a folder somewhere and it'll get picked up and reloaded every time my config is reloaded?

I've [read this](https://github.com/Hammerspoon/hammerspoon/blob/master/CONTRIBUTING.md#writing-a-pure-lua-extension) and [seen this](https://github.com/asmagill/HS_ModuleWalkthrough) but neither were explicit about how to test this simple case of a pure lua extension. Thanks!

**Comment by bradparks** [comment] 2015-09-18 15:59
Hey... I'm sure it was obvious to most, but I just figured out how to test a pure lua extension easy... All I had to do was create a new folder at:

/Applications/Hammerspoon.app/Contents/Resources/extensions/hs/my_extension

and drop the init.lua file in there, and it's working great. Thanks!

**Comment by cmsj** [comment] 2015-09-18 19:32
@bradparks yep, that works. you can also put it into ~/.hammerspoon/ which may be easier

**Comment by lowne** [comment] 2015-09-19 21:54
yes, better put it into `~/.hammerspoon/hs/my_extension/init.lua`, this way your code will survive app updates etc.

**Comment by bradparks** [comment] 2015-09-19 23:30
ah! good point... thanks a bunch!

**Comment by cmsj** [comment] 2017-09-04 19:40
I'm going to close this out - we have Spoons now, which likely cover much of what this issue was intended to cover.

**Closed by cmsj** 2017-09-04 19:40 UTC
Labels: docs, help wanted
